<?php
require __DIR__.'/lib.php'; gw_require_login(); $db=gw_db();
$period=max(1,min(365,(int)($_GET['days']??30))); $cut=date('Y-m-d H:i:s',time()-$period*86400);
$metrics=[
 'visitors'=>(int)$db->prepare('SELECT COUNT(*) FROM gw_visitors WHERE last_seen>=?')->execute([$cut]),
];
$st=$db->prepare('SELECT COUNT(*) FROM gw_visitors WHERE last_seen>=?');$st->execute([$cut]);$visitorCount=(int)$st->fetchColumn();
$st=$db->prepare('SELECT COUNT(*) FROM gw_visitors WHERE last_seen>=? AND (name IS NOT NULL AND name<>"")');$st->execute([$cut]);$identified=(int)$st->fetchColumn();
$st=$db->prepare('SELECT COUNT(*) FROM gw_events WHERE created_at>=? AND event_type IN ("quote_click","sample_click","whatsapp_click","docs_click")');$st->execute([$cut]);$intent=(int)$st->fetchColumn();
$st=$db->prepare('SELECT COALESCE(MAX(score),0) FROM gw_visitors WHERE last_seen>=?');$st->execute([$cut]);$maxScore=(int)$st->fetchColumn();
$status=$_GET['status']??'';$q=trim($_GET['q']??'');
$sql='SELECT * FROM gw_visitors WHERE last_seen>=?';$args=[$cut];
if($status!==''){ $sql.=' AND status=?';$args[]=$status; }
if($q!==''){ $sql.=' AND (name LIKE ? OR company LIKE ? OR email LIKE ? OR phone LIKE ? OR visitor_key LIKE ?)';$needle='%'.$q.'%';array_push($args,$needle,$needle,$needle,$needle,$needle); }
$sql.=' ORDER BY score DESC,last_seen DESC LIMIT 250';$st=$db->prepare($sql);$st->execute($args);$visitors=$st->fetchAll();
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GREEN WORLD CRM</title><link rel="stylesheet" href="style.css"></head><body><header class="crm-top"><div><div class="crm-brand"><span>GW</span><b>GREEN WORLD CRM</b></div><small>Painel interno • não aparece no site público</small></div><nav><a href="index.php">Dashboard</a><a href="logout.php">Sair</a></nav></header><main class="crm-wrap">
<section class="hero-admin"><div><p>INTELIGÊNCIA COMERCIAL</p><h1>Visitantes e oportunidades</h1><span>Priorize quem demonstra maior interesse nos produtos da Green World.</span></div><form class="period" method="get"><select name="days" onchange="this.form.submit()"><option value="7" <?=$period===7?'selected':''?>>7 dias</option><option value="30" <?=$period===30?'selected':''?>>30 dias</option><option value="90" <?=$period===90?'selected':''?>>90 dias</option><option value="365" <?=$period===365?'selected':''?>>1 ano</option></select></form></section>
<section class="cards"><article><span>Visitantes</span><strong><?=$visitorCount?></strong><small>No período</small></article><article><span>Leads identificados</span><strong><?=$identified?></strong><small>Com nome cadastrado</small></article><article><span>Ações de intenção</span><strong><?=$intent?></strong><small>WhatsApp, cotação, amostra e docs</small></article><article><span>Maior Lead Score</span><strong><?=$maxScore?></strong><small>Prioridade comercial</small></article></section>
<section class="panel"><div class="panel-head"><div><h2>Pipeline de visitantes</h2><p>Visitantes anônimos ganham histórico e score; você pode identificá-los manualmente quando o contato chegar.</p></div><form class="filters" method="get"><input type="hidden" name="days" value="<?=$period?>"><input name="q" value="<?=gw_e($q)?>" placeholder="Buscar lead..."><select name="status"><option value="">Todos os status</option><?php foreach(gw_statuses() as $s):?><option <?=$status===$s?'selected':''?>><?=gw_e($s)?></option><?php endforeach;?></select><button>Filtrar</button></form></div><div class="table-wrap"><table><thead><tr><th>Lead</th><th>Score</th><th>Status</th><th>Interesse / origem</th><th>Visitas</th><th>Última atividade</th></tr></thead><tbody><?php foreach($visitors as $v):?><tr onclick="location.href='visitor.php?id=<?=$v['id']?>'"><td><b><?=gw_e($v['name'] ?: 'Visitante #'.$v['id'])?></b><small><?=gw_e($v['company'] ?: substr($v['visitor_key'],0,13).'…')?></small></td><td><span class="score <?=$v['score']>=60?'hot':($v['score']>=25?'warm':'')?>"><?=$v['score']?></span></td><td><span class="status"><?=gw_e($v['status'])?></span></td><td><b><?=gw_e($v['last_path'] ?: '—')?></b><small><?=gw_e($v['source'] ?: ($v['first_referrer']?'Referência externa':'Direto'))?></small></td><td><?=$v['visit_count']?></td><td><?=gw_e(date('d/m/Y H:i',strtotime($v['last_seen'])))?></td></tr><?php endforeach;?><?php if(!$visitors):?><tr><td colspan="6" class="empty">Nenhum visitante registrado ainda.</td></tr><?php endif;?></tbody></table></div></section>
</main></body></html>
