<?php
require __DIR__.'/lib.php';gw_require_login();$db=gw_db();$id=(int)($_GET['id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!gw_check_csrf($_POST['csrf']??'')){http_response_code(403);exit('CSRF inválido');}
 $st=$db->prepare('UPDATE gw_visitors SET name=?,company=?,email=?,phone=?,status=?,notes=? WHERE id=?');
 $status=in_array($_POST['status']??'',gw_statuses(),true)?$_POST['status']:'Novo visitante';
 $st->execute([trim($_POST['name']??''),trim($_POST['company']??''),trim($_POST['email']??''),trim($_POST['phone']??''),$status,trim($_POST['notes']??''),$id]);
 header('Location: visitor.php?id='.$id.'&saved=1');exit;
}
$st=$db->prepare('SELECT * FROM gw_visitors WHERE id=?');$st->execute([$id]);$v=$st->fetch();if(!$v){http_response_code(404);exit('Lead não encontrado');}
$st=$db->prepare('SELECT * FROM gw_events WHERE visitor_id=? ORDER BY created_at DESC LIMIT 300');$st->execute([$id]);$events=$st->fetchAll();
$labels=['page_view'=>'Página visitada','products_view'=>'Entrou em Produtos','product_open'=>'Abriu produto','whatsapp_click'=>'Clicou no WhatsApp','quote_click'=>'Solicitou cotação','sample_click'=>'Solicitou amostra','docs_click'=>'Solicitou documentação','email_click'=>'Clicou no e-mail'];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lead | GREEN WORLD CRM</title><link rel="stylesheet" href="style.css"></head><body><header class="crm-top"><div class="crm-brand"><span>GW</span><b>GREEN WORLD CRM</b></div><nav><a href="index.php">← Dashboard</a><a href="logout.php">Sair</a></nav></header><main class="crm-wrap"><section class="lead-header"><div><p>LEAD #<?=$v['id']?></p><h1><?=gw_e($v['name'] ?: 'Visitante anônimo')?></h1><span>Primeira visita: <?=gw_e(date('d/m/Y H:i',strtotime($v['first_seen'])))?> • Última: <?=gw_e(date('d/m/Y H:i',strtotime($v['last_seen'])))?></span></div><div class="big-score"><small>LEAD SCORE</small><strong><?=$v['score']?></strong></div></section><?php if(isset($_GET['saved'])):?><div class="success wide">Lead atualizado.</div><?php endif;?><div class="lead-grid"><section class="panel editor"><h2>Dados comerciais</h2><form method="post"><input type="hidden" name="csrf" value="<?=gw_e(gw_csrf())?>"><label>Nome<input name="name" value="<?=gw_e($v['name'])?>" placeholder="Identifique quando o cliente entrar em contato"></label><label>Empresa<input name="company" value="<?=gw_e($v['company'])?>"></label><div class="two"><label>E-mail<input type="email" name="email" value="<?=gw_e($v['email'])?>"></label><label>Telefone<input name="phone" value="<?=gw_e($v['phone'])?>"></label></div><label>Status<select name="status"><?php foreach(gw_statuses() as $s):?><option <?=$v['status']===$s?'selected':''?>><?=gw_e($s)?></option><?php endforeach;?></select></label><label>Anotações<textarea name="notes" rows="7" placeholder="Necessidade, volume, produto de interesse, próximos passos..."><?=gw_e($v['notes'])?></textarea></label><button>Salvar lead</button></form></section><section class="panel timeline"><div class="panel-head"><div><h2>Histórico do visitante</h2><p><?=$v['visit_count']?> visitas • <?=$v['event_count']?> eventos registrados</p></div></div><?php foreach($events as $e):?><article class="event"><span class="event-dot"></span><div><b><?=gw_e($labels[$e['event_type']]??$e['event_type'])?></b><?php if($e['product_code']):?><em><?=gw_e($e['product_code'])?></em><?php endif;?><p><?=gw_e($e['label'] ?: $e['path'])?></p><small><?=gw_e(date('d/m/Y H:i',strtotime($e['created_at'])))?></small></div></article><?php endforeach;?></section></div></main></body></html>
