(function(){
'use strict';
const FLAGS={pt:'🇧🇷',en:'🇺🇸',es:'🇪🇸'};
const LABELS={pt:'Português',en:'English',es:'Español'};

const EXACT={
en:{
'Atuamos globalmente':'We operate globally','🌐 Atuamos globalmente':'🌐 We operate globally','▣ Atendimento ao mercado nacional e internacional':'▣ Serving domestic and international markets',
'PRODUTOS':'PRODUCTS','SOLUÇÕES':'SOLUTIONS','QUALIDADE':'QUALITY','COMÉRCIO INTERNACIONAL':'INTERNATIONAL TRADE','SOBRE NÓS':'ABOUT US','CONTATO':'CONTACT','SOLICITAR COTAÇÃO →':'REQUEST A QUOTE →',
'SOLUÇÕES QUÍMICAS':'CHEMICAL SOLUTIONS','Soluções químicas':'Chemical solutions','para um mundo':'for a','mais sustentável.':'more sustainable world.','Produtos de alta qualidade para resinas, adesivos, tintas, borrachas e outras aplicações industriais, com segurança, tecnologia e compromisso com o futuro.':'High-quality products for resins, adhesives, paints, rubber and other industrial applications, combining safety, technology and commitment to the future.',
'CONHEÇA NOSSOS PRODUTOS →':'EXPLORE OUR PRODUCTS →','FALAR COM ESPECIALISTA ◉':'TALK TO A SPECIALIST ◉','Da floresta':'From the forest','para as indústrias':'to industries','do mundo.':'worldwide.',
'ATUAMOS':'WE OPERATE','GLOBALMENTE':'GLOBALLY','PRODUTOS NO CATÁLOGO':'PRODUCTS IN THE CATALOG','CONTATO COM AS FLORESTAS':'CONNECTED TO THE FORESTS','DESDE O NOSSO INÍCIO':'SINCE OUR BEGINNING','Mais de 25 anos de história':'More than 25 years of history','COMPROMISSO COM QUALIDADE':'COMMITMENT TO QUALITY',
'Quem Somos':'Who We Are','Nossa história começou na floresta. Há mais de 25 anos trabalhamos com a base florestal de Pinus — começamos como resineiros, extraindo a matéria-prima que hoje processamos nós mesmos.':'Our story began in the forest. For more than 25 years we have worked with the Pinus forestry base — we started as resin tappers, extracting the raw material that we now process ourselves.','Dali, verticalizamos para o processamento de breu e terebentina e mais recentemente demos um novo passo: os derivados de breu.':'From there, we vertically integrated into rosin and turpentine processing and, more recently, took a new step: rosin derivatives.','Hoje a Green World Chemicals opera em Alambari (SP), processando goma de Pinus para atender indústrias no Brasil e no exterior.':'Today Green World Chemicals operates in Alambari, São Paulo, processing pine gum to serve industries in Brazil and abroad.','SOLICITE SUA AMOSTRA →':'REQUEST A SAMPLE →','Mais de 25 anos':'More than 25 years','de história':'of history','Compromisso':'Commitment','com as florestas':'to the forests','Atuação':'Presence','internacional':'international',
'Um portfólio completo':'A complete portfolio','derivado da floresta.':'derived from the forest.','Produtos de alta performance, desenvolvidos a partir da resina de Pinus, para atender às mais diversas aplicações industriais, com qualidade, rastreabilidade e fornecimento confiável.':'High-performance products developed from pine resin to serve a wide range of industrial applications, with quality, traceability and reliable supply.','Breu':'Gum Rosin','Terebintina':'Turpentine','Derivados de Breu':'Gum Rosin Derivatives','Resinas Especiais':'Special Resins','Outras Soluções':'Other Solutions',
'SEGMENTOS ATENDIDOS':'MARKETS SERVED','Soluções para':'Solutions for','cada segmento.':'every market.','Atendemos indústrias em diferentes mercados, oferecendo soluções químicas sob medida, com qualidade, segurança e suporte técnico.':'We serve industries across different markets, offering tailored chemical solutions with quality, safety and technical support.','FALAR COM NOSSO TIME →':'TALK TO OUR TEAM →','Indústria':'Industry','Matérias-primas para processos industriais.':'Raw materials for industrial processes.','Construção':'Construction','Soluções com qualidade e segurança.':'Solutions with quality and safety.','Agricultura':'Agriculture','Insumos para aumentar o rendimento.':'Inputs to increase yield.','Adesivos e Tintas':'Adhesives and Paints','Resinas para alto desempenho.':'Resins for high performance.','Outros Segmentos':'Other Markets','Atendimento a diversas aplicações industriais.':'Solutions for a wide range of industrial applications.',
'QUALIDADE E SEGURANÇA':'QUALITY AND SAFETY','Compromisso com':'Commitment to','a excelência':'excellence','Processos rigorosos, controle de qualidade e rastreabilidade em todas as etapas.':'Rigorous processes, quality control and traceability at every stage.','✓ Controle de Qualidade':'✓ Quality Control','Análises e testes para garantir a qualidade dos produtos.':'Analysis and testing to ensure product quality.','▣ Certificações':'▣ Certifications','Processos orientados por padrões de qualidade.':'Processes guided by quality standards.','◉ Segurança':'◉ Safety','Produtos manuseados e armazenados com responsabilidade.':'Products handled and stored responsibly.','↻ Rastreabilidade':'↻ Traceability','Controle da cadeia logística dos nossos produtos.':'Control of our products’ logistics chain.','♧ Laboratório próprio':'♧ In-house laboratory','♙ Profissionais qualificados':'♙ Qualified professionals','♙ Processos seguros':'♙ Safe processes','✓ Melhoria contínua':'✓ Continuous improvement',
'Conectando soluções':'Connecting solutions','ao mundo':'to the world','Exportação e atendimento B2B com suporte especializado.':'Exports and B2B service with specialized support.','Na GWC o cliente internacional negocia diretamente com quem produz — sem camadas de intermediação, com rastreabilidade de lote e especificação técnica consistente embarque após embarque.':'At GWC, international customers negotiate directly with the producer — without intermediary layers, with batch traceability and consistent technical specifications shipment after shipment.','Atendemos embarques em contêineres FCL e isotanque, nas condições CIF ou FOB, com toda a documentação de exportação preparada internamente: certificado de análise, ficha de segurança (MSDS/SDS), packing list, certificado de origem e embalagem certificada para produto classificado.':'We handle FCL container and isotank shipments under CIF or FOB terms, with all export documentation prepared in-house: certificate of analysis, safety data sheet (MSDS/SDS), packing list, certificate of origin and certified packaging for classified products.','Produtor de origem — breu, derivados e terebentina de goma de pinus brasileira':'Original producer — rosin, derivatives and turpentine from Brazilian pine gum','Embarques em FCL e isotanque, CIF ou FOB':'FCL and isotank shipments, CIF or FOB','Documentação técnica e aduaneira completa':'Complete technical and customs documentation','Atendimento B2B direto, com suporte técnico':'Direct B2B service with technical support','FALAR SOBRE EXPORTAÇÃO →':'TALK ABOUT EXPORTS →',
'Precisa de uma cotação?':'Need a quote?','Nossa equipe está pronta para atender você.':'Our team is ready to assist you.','Soluções químicas de alta qualidade para um mundo em constante evolução.':'High-quality chemical solutions for a constantly evolving world.','NAVEGAÇÃO':'NAVIGATION','PRODUTOS':'PRODUCTS','SUPORTE':'SUPPORT','Fale Conosco':'Contact Us','Solicitar Cotação':'Request a Quote','Política de Privacidade':'Privacy Policy','Todos os direitos reservados.':'All rights reserved.','© 2026 GREEN WORLD. Todos os direitos reservados.':'© 2026 GREEN WORLD. All rights reserved.',
'PORTFÓLIO GREEN WORLD':'GREEN WORLD PORTFOLIO','Nossos':'Our','Produtos':'Products','Soluções à base de resina de Pinus para diferentes aplicações industriais. Consulte famílias, códigos, especificações, aplicações e resumo técnico.':'Pine-resin-based solutions for different industrial applications. Browse families, codes, specifications, applications and technical summaries.','LINHAS DE PRODUTOS':'PRODUCT LINES','Soluções de origem renovável':'Renewable-source solutions','para diferentes mercados':'for different markets','Conheça as famílias de produtos GREEN WORLD. Selecione uma linha para consultar códigos, especificações, aplicações e solicitar cotação ou amostra.':'Explore GREEN WORLD product families. Select a line to view codes, specifications, applications and request a quote or sample.','LINHA':'LINE','APLICAÇÃO':'APPLICATION','TODOS':'ALL','TODAS':'ALL','APLICAÇÕES':'APPLICATIONS','LINHA GREEN WORLD':'GREEN WORLD LINE','Nenhum produto encontrado para os filtros selecionados.':'No products found for the selected filters.','SOLICITAR AMOSTRA →':'REQUEST A SAMPLE →','SOLICITAR DOCUMENTAÇÃO TÉCNICA →':'REQUEST TECHNICAL DOCUMENTATION →','Consulte nossa equipe comercial.':'Contact our sales team.','produto':'product','produtos':'products','linha':'line','linhas':'lines','aplicação':'application','aplicações':'applications',
'Goma Resina':'Crude Gum Resin','Resinas Fumáricas':'Fumaric Resins','Resinas Maleicas':'Maleic Resins','Ésteres de Breu':'Rosin Esters','Éster de Glicerol':'Glycerol Ester','Éster de Pentaeritritol':'Pentaerythritol Ester','Éster de Trietilenoglicol':'Triethylene Glycol Ester','Ésteres Food Grade':'Food Grade Esters','Resinas de Marcação Viária':'Road-Marking Resins','Sabões':'Rosin Soaps','Emulsões':'Emulsions','Plastificantes':'Plasticizers','Aditivos Agro':'Agricultural Additives','Fabricação de Resinas':'Resin Manufacturing',
'COTAÇÃO':'QUOTE','Cotação':'Quote','Amostra':'Sample','Abrir contatos':'Open contacts','Voltar ao topo':'Back to top'
},
es:{
'Atuamos globalmente':'Actuamos globalmente','🌐 Atuamos globalmente':'🌐 Actuamos globalmente','▣ Atendimento ao mercado nacional e internacional':'▣ Atendemos mercados nacionales e internacionales',
'HOME':'INICIO','PRODUTOS':'PRODUCTOS','SOLUÇÕES':'SOLUCIONES','QUALIDADE':'CALIDAD','COMÉRCIO INTERNACIONAL':'COMERCIO INTERNACIONAL','SOBRE NÓS':'SOBRE NOSOTROS','CONTATO':'CONTACTO','SOLICITAR COTAÇÃO →':'SOLICITAR COTIZACIÓN →',
'SOLUÇÕES QUÍMICAS':'SOLUCIONES QUÍMICAS','Soluções químicas':'Soluciones químicas','para um mundo':'para un mundo','mais sustentável.':'más sostenible.','Produtos de alta qualidade para resinas, adesivos, tintas, borrachas e outras aplicações industriais, com segurança, tecnologia e compromisso com o futuro.':'Productos de alta calidad para resinas, adhesivos, pinturas, cauchos y otras aplicaciones industriales, con seguridad, tecnología y compromiso con el futuro.','CONHEÇA NOSSOS PRODUTOS →':'CONOZCA NUESTROS PRODUCTOS →','FALAR COM ESPECIALISTA ◉':'HABLAR CON UN ESPECIALISTA ◉','Da floresta':'Del bosque','para as indústrias':'a las industrias','do mundo.':'del mundo.',
'ATUAMOS':'ACTUAMOS','GLOBALMENTE':'GLOBALMENTE','PRODUTOS NO CATÁLOGO':'PRODUCTOS EN EL CATÁLOGO','CONTATO COM AS FLORESTAS':'CONTACTO CON LOS BOSQUES','DESDE O NOSSO INÍCIO':'DESDE NUESTRO INICIO','Mais de 25 anos de história':'Más de 25 años de historia','COMPROMISSO COM QUALIDADE':'COMPROMISO CON LA CALIDAD',
'Quem Somos':'Quiénes Somos','Nossa história começou na floresta. Há mais de 25 anos trabalhamos com a base florestal de Pinus — começamos como resineiros, extraindo a matéria-prima que hoje processamos nós mesmos.':'Nuestra historia comenzó en el bosque. Desde hace más de 25 años trabajamos con la base forestal de Pinus — comenzamos como resineros, extrayendo la materia prima que hoy procesamos nosotros mismos.','Dali, verticalizamos para o processamento de breu e terebentina e mais recentemente demos um novo passo: os derivados de breu.':'A partir de allí, nos integramos verticalmente al procesamiento de colofonia y trementina y, más recientemente, dimos un nuevo paso: los derivados de colofonia.','Hoje a Green World Chemicals opera em Alambari (SP), processando goma de Pinus para atender indústrias no Brasil e no exterior.':'Hoy Green World Chemicals opera en Alambari (SP), procesando goma de Pinus para atender industrias en Brasil y en el exterior.','SOLICITE SUA AMOSTRA →':'SOLICITE UNA MUESTRA →','Mais de 25 anos':'Más de 25 años','de história':'de historia','Compromisso':'Compromiso','com as florestas':'con los bosques','Atuação':'Presencia','internacional':'internacional',
'Um portfólio completo':'Un portafolio completo','derivado da floresta.':'derivado del bosque.','Produtos de alta performance, desenvolvidos a partir da resina de Pinus, para atender às mais diversas aplicações industriais, com qualidade, rastreabilidade e fornecimento confiável.':'Productos de alto rendimiento, desarrollados a partir de resina de Pinus para atender las más diversas aplicaciones industriales, con calidad, trazabilidad y suministro confiable.','Breu':'Colofonia','Terebintina':'Trementina','Derivados de Breu':'Derivados de Colofonia','Resinas Especiais':'Resinas Especiales','Outras Soluções':'Otras Soluciones',
'SEGMENTOS ATENDIDOS':'SEGMENTOS ATENDIDOS','Soluções para':'Soluciones para','cada segmento.':'cada segmento.','Atendemos indústrias em diferentes mercados, oferecendo soluções químicas sob medida, com qualidade, segurança e suporte técnico.':'Atendemos industrias en diferentes mercados, ofreciendo soluciones químicas a medida, con calidad, seguridad y soporte técnico.','FALAR COM NOSSO TIME →':'HABLAR CON NUESTRO EQUIPO →','Indústria':'Industria','Matérias-primas para processos industriais.':'Materias primas para procesos industriales.','Construção':'Construcción','Soluções com qualidade e segurança.':'Soluciones con calidad y seguridad.','Agricultura':'Agricultura','Insumos para aumentar o rendimento.':'Insumos para aumentar el rendimiento.','Adesivos e Tintas':'Adhesivos y Pinturas','Resinas para alto desempenho.':'Resinas para alto rendimiento.','Outros Segmentos':'Otros Segmentos','Atendimento a diversas aplicações industriais.':'Atención a diversas aplicaciones industriales.',
'QUALIDADE E SEGURANÇA':'CALIDAD Y SEGURIDAD','Compromisso com':'Compromiso con','a excelência':'la excelencia','Processos rigorosos, controle de qualidade e rastreabilidade em todas as etapas.':'Procesos rigurosos, control de calidad y trazabilidad en todas las etapas.','✓ Controle de Qualidade':'✓ Control de Calidad','Análises e testes para garantir a qualidade dos produtos.':'Análisis y pruebas para garantizar la calidad de los productos.','▣ Certificações':'▣ Certificaciones','Processos orientados por padrões de qualidade.':'Procesos orientados por estándares de calidad.','◉ Segurança':'◉ Seguridad','Produtos manuseados e armazenados com responsabilidade.':'Productos manipulados y almacenados con responsabilidad.','↻ Rastreabilidade':'↻ Trazabilidad','Controle da cadeia logística dos nossos produtos.':'Control de la cadena logística de nuestros productos.','♧ Laboratório próprio':'♧ Laboratorio propio','♙ Profissionais qualificados':'♙ Profesionales calificados','♙ Processos seguros':'♙ Procesos seguros','✓ Melhoria contínua':'✓ Mejora continua',
'Conectando soluções':'Conectando soluciones','ao mundo':'con el mundo','Exportação e atendimento B2B com suporte especializado.':'Exportación y atención B2B con soporte especializado.','Na GWC o cliente internacional negocia diretamente com quem produz — sem camadas de intermediação, com rastreabilidade de lote e especificação técnica consistente embarque após embarque.':'En GWC el cliente internacional negocia directamente con quien produce — sin capas de intermediación, con trazabilidad de lote y especificación técnica consistente embarque tras embarque.','Atendemos embarques em contêineres FCL e isotanque, nas condições CIF ou FOB, com toda a documentação de exportação preparada internamente: certificado de análise, ficha de segurança (MSDS/SDS), packing list, certificado de origem e embalagem certificada para produto classificado.':'Atendemos embarques en contenedores FCL e isotanque, en condiciones CIF o FOB, con toda la documentación de exportación preparada internamente: certificado de análisis, ficha de seguridad (MSDS/SDS), packing list, certificado de origen y embalaje certificado para producto clasificado.','Produtor de origem — breu, derivados e terebentina de goma de pinus brasileira':'Productor de origen — colofonia, derivados y trementina de goma de pino brasileña','Embarques em FCL e isotanque, CIF ou FOB':'Embarques en FCL e isotanque, CIF o FOB','Documentação técnica e aduaneira completa':'Documentación técnica y aduanera completa','Atendimento B2B direto, com suporte técnico':'Atención B2B directa, con soporte técnico','FALAR SOBRE EXPORTAÇÃO →':'HABLAR SOBRE EXPORTACIÓN →',
'Precisa de uma cotação?':'¿Necesita una cotización?','Nossa equipe está pronta para atender você.':'Nuestro equipo está listo para atenderle.','Soluções químicas de alta qualidade para um mundo em constante evolução.':'Soluciones químicas de alta calidad para un mundo en constante evolución.','NAVEGAÇÃO':'NAVEGACIÓN','PRODUTOS':'PRODUCTOS','SUPORTE':'SOPORTE','Fale Conosco':'Contáctenos','Solicitar Cotação':'Solicitar Cotización','Política de Privacidade':'Política de Privacidad','© 2026 GREEN WORLD. Todos os direitos reservados.':'© 2026 GREEN WORLD. Todos los derechos reservados.',
'PORTFÓLIO GREEN WORLD':'PORTAFOLIO GREEN WORLD','Nossos':'Nuestros','Produtos':'Productos','Soluções à base de resina de Pinus para diferentes aplicações industriais. Consulte famílias, códigos, especificações, aplicações e resumo técnico.':'Soluciones a base de resina de Pinus para diferentes aplicaciones industriales. Consulte familias, códigos, especificaciones, aplicaciones y resumen técnico.','LINHAS DE PRODUTOS':'LÍNEAS DE PRODUCTOS','Soluções de origem renovável':'Soluciones de origen renovable','para diferentes mercados':'para diferentes mercados','Conheça as famílias de produtos GREEN WORLD. Selecione uma linha para consultar códigos, especificações, aplicações e solicitar cotação ou amostra.':'Conozca las familias de productos GREEN WORLD. Seleccione una línea para consultar códigos, especificaciones, aplicaciones y solicitar cotización o muestra.','LINHA':'LÍNEA','APLICAÇÃO':'APLICACIÓN','TODOS':'TODOS','TODAS':'TODAS','APLICAÇÕES':'APLICACIONES','LINHA GREEN WORLD':'LÍNEA GREEN WORLD','Nenhum produto encontrado para os filtros selecionados.':'No se encontraron productos para los filtros seleccionados.','SOLICITAR AMOSTRA →':'SOLICITAR MUESTRA →','SOLICITAR DOCUMENTAÇÃO TÉCNICA →':'SOLICITAR DOCUMENTACIÓN TÉCNICA →','Consulte nossa equipe comercial.':'Consulte a nuestro equipo comercial.','produto':'producto','produtos':'productos','linha':'línea','linhas':'líneas','aplicação':'aplicación','aplicações':'aplicaciones',
'Goma Resina':'Goma Resina','Resinas Fumáricas':'Resinas Fumáricas','Resinas Maleicas':'Resinas Maleicas','Ésteres de Breu':'Ésteres de Colofonia','Éster de Glicerol':'Éster de Glicerol','Éster de Pentaeritritol':'Éster de Pentaeritritol','Éster de Trietilenoglicol':'Éster de Trietilenglicol','Ésteres Food Grade':'Ésteres Food Grade','Resinas de Marcação Viária':'Resinas de Marcación Vial','Sabões':'Jabones','Emulsões':'Emulsiones','Plastificantes':'Plastificantes','Aditivos Agro':'Aditivos Agro','Fabricação de Resinas':'Fabricación de Resinas','Cotação':'Cotización','Amostra':'Muestra','Abrir contatos':'Abrir contactos','Voltar ao topo':'Volver arriba'
}}
;

const FAMILY={
en:{'GOMA RESINA':'CRUDE GUM RESIN','BREU':'GUM ROSIN','TEREBINTINA':'TURPENTINE','RESINAS FUMÁRICAS':'FUMARIC RESINS','RESINAS MALEICAS':'MALEIC RESINS','ESTER DE GLICEROL':'GLYCEROL ESTER','ESTER DE PENTAERITRITOL':'PENTAERYTHRITOL ESTER','ESTER DE TRIETILENOGLICOL':'TRIETHYLENE GLYCOL ESTER','RESINAS DE MARCAÇÃO VIÁRIA':'ROAD-MARKING RESINS','SABÕES':'ROSIN SOAPS','EMULSÕES':'EMULSIONS','PLASTIFICANTES':'PLASTICIZERS','ADITIVOS AGRO':'AGRICULTURAL ADDITIVES','FABRICAÇÃO DE RESINAS':'RESIN MANUFACTURING','ESTERES FOOD GRADE':'FOOD GRADE ESTERS'},
es:{'GOMA RESINA':'GOMA RESINA','BREU':'COLOFONIA','TEREBINTINA':'TREMENTINA','RESINAS FUMÁRICAS':'RESINAS FUMÁRICAS','RESINAS MALEICAS':'RESINAS MALEICAS','ESTER DE GLICEROL':'ÉSTER DE GLICEROL','ESTER DE PENTAERITRITOL':'ÉSTER DE PENTAERITRITOL','ESTER DE TRIETILENOGLICOL':'ÉSTER DE TRIETILENGLICOL','RESINAS DE MARCAÇÃO VIÁRIA':'RESINAS DE MARCACIÓN VIAL','SABÕES':'JABONES DE COLOFONIA','EMULSÕES':'EMULSIONES','PLASTIFICANTES':'PLASTIFICANTES','ADITIVOS AGRO':'ADITIVOS AGRO','FABRICAÇÃO DE RESINAS':'FABRICACIÓN DE RESINAS','ESTERES FOOD GRADE':'ÉSTERES FOOD GRADE'}};
const APP={
en:{'TINTAS FLEXOGRÁFICAS':'FLEXOGRAPHIC INKS','TINTAS E VERNIZES BASE SOLVENTE':'SOLVENT-BASED PAINTS AND VARNISHES','TINTAS DE MARCAÇÃO DE ESTRADA':'ROAD-MARKING PAINTS','ADESIVOS HOT-MELT E BASE SOLVENTE':'HOT-MELT AND SOLVENT-BASED ADHESIVES','LINHA AGRO':'AGRICULTURAL LINE','PLASTIFICANTES':'PLASTICIZERS','FABRICAÇÃO DE RESINAS ESPECIAIS':'SPECIALTY RESIN MANUFACTURING','CONSTRUÇÃO CIVIL':'CONSTRUCTION','CERAS DEPILATÓRIAS':'DEPILATORY WAXES','FOOD GRADE':'FOOD GRADE','FABRICAÇÃO DE BORRACHAS E PNEUS':'RUBBER AND TIRE MANUFACTURING','RECOBRIMENTO DE FRUTOS':'FRUIT COATING','ADESIVOS BASE ÁGUA':'WATER-BASED ADHESIVES','ASFALTO':'ASPHALT'},
es:{'TINTAS FLEXOGRÁFICAS':'TINTAS FLEXOGRÁFICAS','TINTAS E VERNIZES BASE SOLVENTE':'PINTURAS Y BARNICES BASE SOLVENTE','TINTAS DE MARCAÇÃO DE ESTRADA':'PINTURAS DE MARCACIÓN VIAL','ADESIVOS HOT-MELT E BASE SOLVENTE':'ADHESIVOS HOT-MELT Y BASE SOLVENTE','LINHA AGRO':'LÍNEA AGRO','PLASTIFICANTES':'PLASTIFICANTES','FABRICAÇÃO DE RESINAS ESPECIAIS':'FABRICACIÓN DE RESINAS ESPECIALES','CONSTRUÇÃO CIVIL':'CONSTRUCCIÓN CIVIL','CERAS DEPILATÓRIAS':'CERAS DEPILATORIAS','FOOD GRADE':'FOOD GRADE','FABRICAÇÃO DE BORRACHAS E PNEUS':'FABRICACIÓN DE CAUCHOS Y NEUMÁTICOS','RECOBRIMENTO DE FRUTOS':'RECUBRIMIENTO DE FRUTOS','ADESIVOS BASE ÁGUA':'ADHESIVOS BASE AGUA','ASFALTO':'ASFALTO'}};


const FULLTEXT={
en:{
"Aditivo desenvolvido para aplicações foliares, auxiliando na preservação e no desempenho de formulações para uso agrícola.":"Additive developed for foliar applications, helping preserve and improve the performance of agricultural formulations.",
"Breu desproporcionado com baixo teor de ácido abiético, indicado para aplicações que exigem elevada resistência à cristalização.":"Disproportionated rosin with low abietic acid content, recommended for applications requiring high crystallization resistance.",
"Breu in natura proveniente exclusivamente da destilação da goma-resina limpa, sem nenhuma modificação química.":"Natural rosin obtained exclusively from the distillation of clean pine gum, without any chemical modification.",
"Breu modificado com adição de éster de breu, desenvolvido especialmente para aplicações em ceras depilatórias.":"Modified rosin with added rosin ester, specially developed for depilatory wax applications.",
"Breu modificado e estabilizado quimicamente para proporcionar maior resistência à cristalização.":"Chemically modified and stabilized rosin designed to provide greater resistance to crystallization.",
"Dispersão aquosa de ésteres de breu, desenvolvida como aditivo de tack para adesivos e outros sistemas à base de água.":"Aqueous dispersion of rosin esters, developed as a tack additive for adhesives and other water-based systems.",
"Goma-resina purificada em fábrica por processos de filtração e remoção de água, destinada à produção de breu e terebintina.":"Pine gum purified at the plant through filtration and water-removal processes, intended for the production of rosin and turpentine.",
"Plastificante à base de breu, desenvolvido para atuar como aditivo plastificante e tackificante em formulações industriais.":"Rosin-based plasticizer developed to act as a plasticizing and tackifying additive in industrial formulations.",
"Resina desenvolvida para fabricação de resinas alquídicas modificadas, contribuindo para o ajuste das propriedades e desempenho da formulação.":"Resin developed for the manufacture of modified alkyd resins, helping adjust formulation properties and performance.",
"Resina fumárica de alta acidez e elevada solubilidade em sistemas alcalinos, desenvolvida para proporcionar alta dureza, rápida secagem e excelente brilho.":"High-acidity fumaric resin with high solubility in alkaline systems, developed to provide high hardness, fast drying and excellent gloss.",
"Resina fumárica de baixa viscosidade e acidez moderada, desenvolvida para aplicações em sistemas que operam em faixa de pH inferior a 9.":"Low-viscosity fumaric resin with moderate acidity, developed for systems operating at pH below 9.",
"Resina fumárica de elevada viscosidade, desenvolvida para tintas e vernizes especiais, proporcionando elevada velocidade de secagem, alto brilho e alta dureza.":"High-viscosity fumaric resin developed for specialty paints and varnishes, providing fast drying, high gloss and high hardness.",
"Resina fumárica modificada, com acidez moderada, desenvolvida para proporcionar elevada velocidade de secagem, alta dureza e excelente brilho.":"Modified fumaric resin with moderate acidity, developed to provide fast drying, high hardness and excellent gloss.",
"Resina maleica de elevado brilho e rápida secagem, desenvolvida para sistemas à base de solvente e nitrocelulose.":"High-gloss, fast-drying maleic resin developed for solvent-based and nitrocellulose systems.",
"Resina maleica para sistemas à base de água e solvente, desenvolvida para proporcionar elevado brilho, boa adesão e rápida secagem.":"Maleic resin for water- and solvent-based systems, developed to provide high gloss, good adhesion and fast drying.",
"Resina modificada com PET e estabilizada, desenvolvida para proporcionar elevada resistência térmica e bom desempenho em diferentes amplitudes de temperatura, contribuindo para a estabilidade e a aderência da tinta.":"PET-modified and stabilized resin developed to provide high thermal resistance and good performance across different temperature ranges, contributing to paint stability and adhesion.",
"Resina modificada e estabilizada, desenvolvida para proporcionar elevada resistência térmica e bom desempenho em diferentes amplitudes de temperatura, contribuindo para a estabilidade e a aderência da tinta.":"Modified and stabilized resin developed to provide high thermal resistance and good performance across different temperature ranges, contributing to paint stability and adhesion.",
"Sabão de breu com baixo teor de ácido abiético, desenvolvido para aplicações em plastificantes e desmoldantes para concreto.":"Rosin soap with low abietic acid content, developed for use in plasticizers and concrete release agents.",
"Sabão de breu com teor mínimo de ácido abiético, desenvolvido especialmente para utilização como agente emulsificante na polimerização de borrachas, além de aplicações em plastificantes e desmoldantes para concreto.":"Rosin soap with minimum abietic acid content, specially developed as an emulsifying agent in rubber polymerization, as well as for use in plasticizers and concrete release agents.",
"Sabão de breu convencional, indicado para fabricação de plastificantes e desmoldantes para artefatos de concreto.":"Conventional rosin soap recommended for the manufacture of plasticizers and release agents for concrete products.",
"Terebintina in natura obtida após o processo de purificação e destilação da goma-resina previamente filtrada.":"Natural turpentine obtained after purification and distillation of previously filtered pine gum.",
"Éster de breu Food Grade, desenvolvido para aplicações em goma de mascar e emulsões cítricas, com especificações controladas para aplicações que exigem padrão Food Grade.":"Food Grade rosin ester developed for chewing gum and citrus emulsion applications, with controlled specifications for uses requiring Food Grade standards.",
"Éster de glicerol modificado e estabilizado, desenvolvido para proporcionar coloração reduzida, maior estabilidade térmica e aumento do tack em formulações adesivas.":"Modified and stabilized glycerol ester developed to provide lighter color, greater thermal stability and increased tack in adhesive formulations.",
"Éster de pentaeritritol estabilizado, desenvolvido para proporcionar coloração reduzida, maior estabilidade térmica e aumento da coesão em formulações adesivas, além de auxiliar na dispersão de borrachas e cargas.":"Stabilized pentaerythritol ester developed to provide lighter color, greater thermal stability and increased cohesion in adhesive formulations, while also assisting the dispersion of rubber and fillers.",
"Éster de trietilenoglicol estabilizado, desenvolvido para proporcionar coloração reduzida, boa estabilidade térmica e elevada resistência à oxidação.":"Stabilized triethylene glycol ester developed to provide lighter color, good thermal stability and high oxidation resistance.",
"ADITIVO DE TACK PARA ADESIVOS E DEMAIS SISTEMAS BASE ÁGUA":"TACK ADDITIVE FOR ADHESIVES AND OTHER WATER-BASED SYSTEMS",
"ADITIVO FOLIAR PARA PRESERVAÇÃO APLICAÇÕES EM GERAL":"FOLIAR ADDITIVE FOR PRESERVATION AND GENERAL APPLICATIONS",
"ADITIVO PLASTIFICANTE E TACKFICANTE":"PLASTICIZING AND TACKIFYING ADDITIVE",
"FABRICAÇÃO DE ADESIVOS HOT-MELT, ADESIVOS BASE SOLVENTE, TINTAS DE MARCAÇÃO DE ESTRADA":"MANUFACTURE OF HOT-MELT ADHESIVES, SOLVENT-BASED ADHESIVES AND ROAD-MARKING PAINTS",
"FABRICAÇÃO DE ADESIVOS HOT-MELT, ADESIVOS BASE SOLVENTE, TINTAS DE MARCAÇÃO DE ESTRADA E BORRACHAS":"MANUFACTURE OF HOT-MELT ADHESIVES, SOLVENT-BASED ADHESIVES, ROAD-MARKING PAINTS AND RUBBER",
"FABRICAÇÃO DE ADESIVOS HOT-MELT, ADESIVOS BASE SOLVENTE, TINTAS DE MARCAÇÃO DE ESTRADA E CERAS DEPILATÓRIAS":"MANUFACTURE OF HOT-MELT ADHESIVES, SOLVENT-BASED ADHESIVES, ROAD-MARKING PAINTS AND DEPILATORY WAXES",
"FABRICAÇÃO DE ADESIVOS PSA, ADESIVOS FLEXIVEIS PARA COLA DE PISOS VINILICOS, ADESIVOS DE BAIXO TG":"MANUFACTURE OF PSA ADHESIVES, FLEXIBLE ADHESIVES FOR VINYL FLOORING AND LOW-TG ADHESIVES",
"FABRICAÇÃO DE BREU E TEREBINTINA":"MANUFACTURE OF ROSIN AND TURPENTINE",
"FABRICAÇÃO DE GOMA DE MASCAR E EMULSÕES CÍTRICAS":"MANUFACTURE OF CHEWING GUM AND CITRUS EMULSIONS",
"FABRICAÇÃO DE PLASTIFICANTES PARA CONCRETO, DESMOLDANTES PARA ARTEFATOS DE CONCRETO":"MANUFACTURE OF CONCRETE PLASTICIZERS AND RELEASE AGENTS FOR CONCRETE PRODUCTS",
"FABRICAÇÃO DE PLASTIFICANTES PARA CONCRETO, DESMOLDANTES PARA ARTEFATOS DE CONCRETO, EMULSIFICANTES PARA POLIMERIZAÇÃO DE BORRACHAS":"MANUFACTURE OF CONCRETE PLASTICIZERS, RELEASE AGENTS FOR CONCRETE PRODUCTS AND EMULSIFIERS FOR RUBBER POLYMERIZATION",
"FABRICAÇÃO DE RESINAS ALQUÍDICAS MODIFICADAS":"MANUFACTURE OF MODIFIED ALKYD RESINS",
"FABRICAÇÃO DE TINTAS DE IMPRESSÃO, TINTAS E VERNIZES INDUSTRIAIS, CERA PARA PISO, RESINAS ALQUÍDICAS, BORRACHA, ACABAMENTO EM COURO":"MANUFACTURE OF PRINTING INKS, INDUSTRIAL PAINTS AND VARNISHES, FLOOR WAX, ALKYD RESINS, RUBBER AND LEATHER FINISHES",
"FABRICAÇÃO DE TINTAS DE IMPRESSÃO, TINTAS E VERNIZES INDUSTRIAIS, CERA PARA PISO, RESINAS ALQUÍDICAS, BORRACHA, ACABAMENTO EM COURO E CERAS PARA RECOBRIMENTO DE FRUTOS":"MANUFACTURE OF PRINTING INKS, INDUSTRIAL PAINTS AND VARNISHES, FLOOR WAX, ALKYD RESINS, RUBBER, LEATHER FINISHES AND FRUIT-COATING WAXES",
"FABRICAÇÃO DE TINTAS DE MARCAÇÃO DE ESTRADA, ADESIVOS HOT-MELT":"MANUFACTURE OF ROAD-MARKING PAINTS AND HOT-MELT ADHESIVES",
"FABRICAÇÃO DE TINTAS DE MARCAÇÃO DE ESTRADA, VERNIZES E TINTAS INDUSTRIAIS BASE SOLVENTE, VERNIZES DE PROTEÇÃO DE MADEIRA":"MANUFACTURE OF ROAD-MARKING PAINTS, SOLVENT-BASED INDUSTRIAL PAINTS AND VARNISHES, AND WOOD-PROTECTION VARNISHES",
"FABRICAÇÃO DE TINTAS E VERNIZES BASE ÁGUA ALCALINA E BASE SOLVENTE":"MANUFACTURE OF ALKALINE WATER-BASED AND SOLVENT-BASED PAINTS AND VARNISHES",
"FABRICAÇÃO DE ÓLEO DE PINHO, ÉSTERES E RESINAS ESPECIAIS":"MANUFACTURE OF PINE OIL, ESTERS AND SPECIALTY RESINS",
"IDEAL PARA FABRICAÇÃO DE CERAS DEPILATÓRIAS":"IDEAL FOR MANUFACTURING DEPILATORY WAXES",
"IDEAL PARA FABRICAÇÃO DE RESINAS E ADESIVOS ESPECIAIS QUE DEMANDEM DE ALTA RESISTÊNCIA A CRISTALIZAÇÃO":"IDEAL FOR MANUFACTURING SPECIALTY RESINS AND ADHESIVES REQUIRING HIGH CRYSTALLIZATION RESISTANCE",
"IDEAL PARA FABRICAÇÃO DE RESINAS, ADESIVOS, TINTAS E CERAS DEPILATÓRIAS":"IDEAL FOR MANUFACTURING RESINS, ADHESIVES, PAINTS AND DEPILATORY WAXES",
"IMPUREZAS":"IMPURITIES","UMIDADE":"MOISTURE","SOLUBILIDADE EM AMÔNIA":"AMMONIA SOLUBILITY","TEOR DE ABIÉTICO(%)":"ABIETIC ACID CONTENT (%)","TEOR DE BETA-PINENO":"BETA-PINENE CONTENT","TEOR DE BICÍCLICOS":"BICYCLIC CONTENT","TEOR DE BREU":"ROSIN CONTENT","TEOR DE TEREBINTINA":"TURPENTINE CONTENT","SABOR":"TASTE","ODOR":"ODOR","HIDROPERÓXIDO (mEq/g)":"HYDROPEROXIDE (mEq/g)","ISENTO":"ABSENT","CARACTERÍSTICO":"CHARACTERISTIC","CONFORME":"COMPLIES","BAIXA":"LOW",
"A Goma Resina é a matéria-prima base da cadeia do Pinus. Obtida pela remoção de água e impurezas, é submetida à destilação para originar o Breu (fração sólida) e a Terebintina (fração volátil), produtos que alimentam toda a linha de derivados. É o ponto de partida da cadeia. produtiva, garantindo rastreabilidade e qualidade desde a origem.":"Pine gum is the base raw material of the Pinus value chain. After water and impurities are removed, it is distilled to produce Rosin (solid fraction) and Turpentine (volatile fraction), which supply the entire derivatives line. It is the starting point of the production chain, ensuring traceability and quality from the source.",
"O Breu (Colofônia) é a resina natural derivada da destilação da goma resina, composta por ácidos resínicos de boa reatividade. É matéria-prima essencial para resinas sintéticas, sizing de papel, sabões, secantes para tintas, vernizes e adesivos. Sua versatilidade e origem renovável o tornam um pilar da indústria química.":"Rosin (colophony) is the natural resin obtained from pine gum distillation, composed of highly reactive resin acids. It is an essential raw material for synthetic resins, paper sizing, soaps, paint driers, varnishes and adhesives. Its versatility and renewable origin make it a key material for the chemical industry.",
"A Terebintina é o solvente natural renovável obtido na destilação da goma resina. Com excelente poder de dissolução, é amplamente utilizada em tintas, vernizes, fragrâncias, cosméticos e na síntese de resinas e terpenos. Uma alternativa sustentável aos solventes sintéticos, mantendo alto desempenho.":"Turpentine is a renewable natural solvent obtained from pine gum distillation. With excellent solvency, it is widely used in paints, varnishes, fragrances, cosmetics and in the synthesis of resins and terpenes. It is a sustainable alternative to synthetic solvents while maintaining high performance.",
"As Resinas Fumáricas são breus modificados com ácido fumárico, desenvolvidos especialmente para tintas de impressão. Com forte adesão ao substrato, secagem rápida e alto brilho, são amplamente utilizadas em tintas flexográficas, rotogravura e offset, além de vernizes e esmaltes sintéticos.":"Fumaric resins are rosins modified with fumaric acid, specially developed for printing inks. With strong substrate adhesion, fast drying and high gloss, they are widely used in flexographic, gravure and offset inks, as well as varnishes and synthetic enamels.",
"As Resinas Maleicas são breus modificados com anidrido maleico, que atuam como agentes modificadores em tintas e vernizes. Proporcionam maior dureza, resistência química e adesão no filme final, com alta compatibilidade com lacas e vernizes nitrocelulósicos.":"Maleic resins are rosins modified with maleic anhydride, used as modifying agents in paints and varnishes. They provide greater hardness, chemical resistance and adhesion in the final film, with high compatibility with lacquers and nitrocellulose varnishes.",
"O Éster de Glicerol é a resina obtida pela esterificação do breu com glicerina. Com alto poder de adesão e ponto de amolecimento equilibrado, é amplamente utilizado em adesivos hot melt, adesivos sensíveis à pressão, tintas de demarcação viária e ceras depilatórias.":"Glycerol ester is a resin obtained by esterifying rosin with glycerin. With high adhesion and a balanced softening point, it is widely used in hot-melt adhesives, pressure-sensitive adhesives, road-marking paints and depilatory waxes.",
"O Éster de Pentaeritritol é a resina da linha com maior ponto de amolecimento e resistência térmica. Indicado para adesivos hot melt de alta performance, adesivos sensíveis à pressão, tintas e revestimentos, oferece excelente adesividade e estabilidade mesmo em condições severas. Também é substituto natural de resinas hidrocarbonicas para a fabricação de asfalto.":"Pentaerythritol ester is the resin in the line with the highest softening point and thermal resistance. Recommended for high-performance hot-melt adhesives, pressure-sensitive adhesives, paints and coatings, it offers excellent adhesion and stability even under severe conditions. It is also a natural substitute for hydrocarbon resins in asphalt production.",
"O Éster de Trietilenoglicol é um éster de breu líquido e viscoso, com excelente aderência, baixa cor e boa resistência ao amarelamento. É amplamente utilizado em adesivos sensíveis à pressão, adesivos hot melt para embalagens, adesivos para construção civil e colagem de pisos.":"Triethylene glycol ester is a liquid, viscous rosin ester with excellent adhesion, light color and good yellowing resistance. It is widely used in pressure-sensitive adhesives, packaging hot-melt adhesives, construction adhesives and flooring applications.",
"As Resinas de Marcação Viária são formuladas para tintas termoplásticas de sinalização horizontal de pavimentos. Proporcionam alta adesão, durabilidade e resistência ao desgaste e às intempéries, garantindo demarcações viárias seguras e de longa vida útil.":"Road-marking resins are formulated for thermoplastic pavement-marking paints. They provide high adhesion, durability and resistance to wear and weathering, ensuring safe, long-lasting road markings.",
"O Sabão de Breu, especialmente o desproporcionado, é um agente tensoativo derivado dos ácidos resínicos, com forte presença na indústria da construção civil. Atua como aditivo plastificante-incorporador de ar em concretos e argamassas, melhorando trabalhabilidade, coesão e resistência ao ciclo gelo-degelo. Os sabões com baixo teor de ácido abiético são excelentes agentes emulsificantes para a industria de polimerização de borrachas.":"Rosin soap, especially disproportionated rosin soap, is a surfactant derived from resin acids and widely used in construction. It acts as a plasticizing and air-entraining additive in concrete and mortar, improving workability, cohesion and freeze-thaw resistance. Low-abietic-acid soaps are excellent emulsifying agents for the rubber polymerization industry.",
"As Emulsões (Dispersões Aquosas) são dispersões de éster de breu em água, livres de solvente e com baixa emissão de VOC. Com excelente compatibilidade com polímeros como borracha natural, acrílico e SBR, são ideais para adesivos sensíveis à pressão em fitas, papel e etiquetas.":"Emulsions (aqueous dispersions) are water dispersions of rosin esters, solvent-free and with low VOC emissions. With excellent compatibility with polymers such as natural rubber, acrylics and SBR, they are ideal for pressure-sensitive adhesives used in tapes, paper and labels.",
"Aditivos plastificantes para a linha de adesivos e tintas em geral de fonte renovavel e isentos dos ftalatos, parafinas e solventes de petróleo e de origem 100% renovável.":"Plasticizing additives for adhesives and paints, from renewable sources and free of phthalates, paraffins and petroleum solvents, with 100% renewable origin.",
"Adjuvantes para preservação de vitaminas, agrotóxicos e insumos em geral utilizados nas linhas agro protegendo os materiais das perdas por intemperies":"Adjuvants for preserving vitamins, crop-protection products and general agricultural inputs, helping protect materials from weather-related losses"
},
es:{
"Aditivo desenvolvido para aplicações foliares, auxiliando na preservação e no desempenho de formulações para uso agrícola.":"Aditivo desarrollado para aplicaciones foliares, ayudando a preservar y mejorar el desempeño de formulaciones para uso agrícola.",
"Breu desproporcionado com baixo teor de ácido abiético, indicado para aplicações que exigem elevada resistência à cristalização.":"Colofonia desproporcionada con bajo contenido de ácido abiético, indicada para aplicaciones que requieren alta resistencia a la cristalización.",
"Breu in natura proveniente exclusivamente da destilação da goma-resina limpa, sem nenhuma modificação química.":"Colofonia natural proveniente exclusivamente de la destilación de goma-resina limpia, sin ninguna modificación química.",
"Breu modificado com adição de éster de breu, desenvolvido especialmente para aplicações em ceras depilatórias.":"Colofonia modificada con adición de éster de colofonia, desarrollada especialmente para aplicaciones en ceras depilatorias.",
"Breu modificado e estabilizado quimicamente para proporcionar maior resistência à cristalização.":"Colofonia modificada y estabilizada químicamente para proporcionar mayor resistencia a la cristalización.",
"Dispersão aquosa de ésteres de breu, desenvolvida como aditivo de tack para adesivos e outros sistemas à base de água.":"Dispersión acuosa de ésteres de colofonia, desarrollada como aditivo de tack para adhesivos y otros sistemas base agua.",
"Goma-resina purificada em fábrica por processos de filtração e remoção de água, destinada à produção de breu e terebintina.":"Goma-resina purificada en fábrica mediante procesos de filtración y eliminación de agua, destinada a la producción de colofonia y trementina.",
"Plastificante à base de breu, desenvolvido para atuar como aditivo plastificante e tackificante em formulações industriais.":"Plastificante a base de colofonia, desarrollado para actuar como aditivo plastificante y tackificante en formulaciones industriales.",
"Resina desenvolvida para fabricação de resinas alquídicas modificadas, contribuindo para o ajuste das propriedades e desempenho da formulação.":"Resina desarrollada para la fabricación de resinas alquídicas modificadas, contribuyendo al ajuste de las propiedades y al desempeño de la formulación.",
"Resina fumárica de alta acidez e elevada solubilidade em sistemas alcalinos, desenvolvida para proporcionar alta dureza, rápida secagem e excelente brilho.":"Resina fumárica de alta acidez y elevada solubilidad en sistemas alcalinos, desarrollada para proporcionar alta dureza, secado rápido y excelente brillo.",
"Resina fumárica de baixa viscosidade e acidez moderada, desenvolvida para aplicações em sistemas que operam em faixa de pH inferior a 9.":"Resina fumárica de baja viscosidad y acidez moderada, desarrollada para aplicaciones en sistemas que operan en un rango de pH inferior a 9.",
"Resina fumárica de elevada viscosidade, desenvolvida para tintas e vernizes especiais, proporcionando elevada velocidade de secagem, alto brilho e alta dureza.":"Resina fumárica de elevada viscosidad, desarrollada para pinturas y barnices especiales, proporcionando alta velocidad de secado, alto brillo y alta dureza.",
"Resina fumárica modificada, com acidez moderada, desenvolvida para proporcionar elevada velocidade de secagem, alta dureza e excelente brilho.":"Resina fumárica modificada, con acidez moderada, desarrollada para proporcionar alta velocidad de secado, alta dureza y excelente brillo.",
"Resina maleica de elevado brilho e rápida secagem, desenvolvida para sistemas à base de solvente e nitrocelulose.":"Resina maleica de alto brillo y secado rápido, desarrollada para sistemas base solvente y nitrocelulosa.",
"Resina maleica para sistemas à base de água e solvente, desenvolvida para proporcionar elevado brilho, boa adesão e rápida secagem.":"Resina maleica para sistemas base agua y solvente, desarrollada para proporcionar alto brillo, buena adhesión y secado rápido.",
"Resina modificada com PET e estabilizada, desenvolvida para proporcionar elevada resistência térmica e bom desempenho em diferentes amplitudes de temperatura, contribuindo para a estabilidade e a aderência da tinta.":"Resina modificada con PET y estabilizada, desarrollada para proporcionar alta resistencia térmica y buen desempeño en diferentes rangos de temperatura, contribuyendo a la estabilidad y adhesión de la pintura.",
"Resina modificada e estabilizada, desenvolvida para proporcionar elevada resistência térmica e bom desempenho em diferentes amplitudes de temperatura, contribuindo para a estabilidade e a aderência da tinta.":"Resina modificada y estabilizada, desarrollada para proporcionar alta resistencia térmica y buen desempeño en diferentes rangos de temperatura, contribuyendo a la estabilidad y adhesión de la pintura.",
"Sabão de breu com baixo teor de ácido abiético, desenvolvido para aplicações em plastificantes e desmoldantes para concreto.":"Jabón de colofonia con bajo contenido de ácido abiético, desarrollado para aplicaciones en plastificantes y desmoldantes para concreto.",
"Sabão de breu com teor mínimo de ácido abiético, desenvolvido especialmente para utilização como agente emulsificante na polimerização de borrachas, além de aplicações em plastificantes e desmoldantes para concreto.":"Jabón de colofonia con contenido mínimo de ácido abiético, desarrollado especialmente como agente emulsificante en la polimerización de cauchos, además de aplicaciones en plastificantes y desmoldantes para concreto.",
"Sabão de breu convencional, indicado para fabricação de plastificantes e desmoldantes para artefatos de concreto.":"Jabón de colofonia convencional, indicado para la fabricación de plastificantes y desmoldantes para productos de concreto.",
"Terebintina in natura obtida após o processo de purificação e destilação da goma-resina previamente filtrada.":"Trementina natural obtenida después del proceso de purificación y destilación de la goma-resina previamente filtrada.",
"Éster de breu Food Grade, desenvolvido para aplicações em goma de mascar e emulsões cítricas, com especificações controladas para aplicações que exigem padrão Food Grade.":"Éster de colofonia Food Grade, desarrollado para aplicaciones en goma de mascar y emulsiones cítricas, con especificaciones controladas para aplicaciones que exigen estándar Food Grade.",
"Éster de glicerol modificado e estabilizado, desenvolvido para proporcionar coloração reduzida, maior estabilidade térmica e aumento do tack em formulações adesivas.":"Éster de glicerol modificado y estabilizado, desarrollado para proporcionar coloración reducida, mayor estabilidad térmica y aumento del tack en formulaciones adhesivas.",
"Éster de pentaeritritol estabilizado, desenvolvido para proporcionar coloração reduzida, maior estabilidade térmica e aumento da coesão em formulações adesivas, além de auxiliar na dispersão de borrachas e cargas.":"Éster de pentaeritritol estabilizado, desarrollado para proporcionar coloración reducida, mayor estabilidad térmica y aumento de la cohesión en formulaciones adhesivas, además de ayudar en la dispersión de cauchos y cargas.",
"Éster de trietilenoglicol estabilizado, desenvolvido para proporcionar coloração reduzida, boa estabilidade térmica e elevada resistência à oxidação.":"Éster de trietilenglicol estabilizado, desarrollado para proporcionar coloración reducida, buena estabilidad térmica y alta resistencia a la oxidación.",
"ADITIVO DE TACK PARA ADESIVOS E DEMAIS SISTEMAS BASE ÁGUA":"ADITIVO DE TACK PARA ADHESIVOS Y DEMÁS SISTEMAS BASE AGUA",
"ADITIVO FOLIAR PARA PRESERVAÇÃO APLICAÇÕES EM GERAL":"ADITIVO FOLIAR PARA PRESERVACIÓN Y APLICACIONES EN GENERAL",
"ADITIVO PLASTIFICANTE E TACKFICANTE":"ADITIVO PLASTIFICANTE Y TACKIFICANTE",
"FABRICAÇÃO DE ADESIVOS HOT-MELT, ADESIVOS BASE SOLVENTE, TINTAS DE MARCAÇÃO DE ESTRADA":"FABRICACIÓN DE ADHESIVOS HOT-MELT, ADHESIVOS BASE SOLVENTE Y PINTURAS DE MARCACIÓN VIAL",
"FABRICAÇÃO DE ADESIVOS HOT-MELT, ADESIVOS BASE SOLVENTE, TINTAS DE MARCAÇÃO DE ESTRADA E BORRACHAS":"FABRICACIÓN DE ADHESIVOS HOT-MELT, ADHESIVOS BASE SOLVENTE, PINTURAS DE MARCACIÓN VIAL Y CAUCHOS",
"FABRICAÇÃO DE ADESIVOS HOT-MELT, ADESIVOS BASE SOLVENTE, TINTAS DE MARCAÇÃO DE ESTRADA E CERAS DEPILATÓRIAS":"FABRICACIÓN DE ADHESIVOS HOT-MELT, ADHESIVOS BASE SOLVENTE, PINTURAS DE MARCACIÓN VIAL Y CERAS DEPILATORIAS",
"FABRICAÇÃO DE ADESIVOS PSA, ADESIVOS FLEXIVEIS PARA COLA DE PISOS VINILICOS, ADESIVOS DE BAIXO TG":"FABRICACIÓN DE ADHESIVOS PSA, ADHESIVOS FLEXIBLES PARA PISOS VINÍLICOS Y ADHESIVOS DE BAJO TG",
"FABRICAÇÃO DE BREU E TEREBINTINA":"FABRICACIÓN DE COLOFONIA Y TREMENTINA",
"FABRICAÇÃO DE GOMA DE MASCAR E EMULSÕES CÍTRICAS":"FABRICACIÓN DE GOMA DE MASCAR Y EMULSIONES CÍTRICAS",
"FABRICAÇÃO DE PLASTIFICANTES PARA CONCRETO, DESMOLDANTES PARA ARTEFATOS DE CONCRETO":"FABRICACIÓN DE PLASTIFICANTES PARA CONCRETO Y DESMOLDANTES PARA PRODUCTOS DE CONCRETO",
"FABRICAÇÃO DE PLASTIFICANTES PARA CONCRETO, DESMOLDANTES PARA ARTEFATOS DE CONCRETO, EMULSIFICANTES PARA POLIMERIZAÇÃO DE BORRACHAS":"FABRICACIÓN DE PLASTIFICANTES PARA CONCRETO, DESMOLDANTES PARA PRODUCTOS DE CONCRETO Y EMULSIFICANTES PARA POLIMERIZACIÓN DE CAUCHOS",
"FABRICAÇÃO DE RESINAS ALQUÍDICAS MODIFICADAS":"FABRICACIÓN DE RESINAS ALQUÍDICAS MODIFICADAS",
"FABRICAÇÃO DE TINTAS DE IMPRESSÃO, TINTAS E VERNIZES INDUSTRIAIS, CERA PARA PISO, RESINAS ALQUÍDICAS, BORRACHA, ACABAMENTO EM COURO":"FABRICACIÓN DE TINTAS DE IMPRESIÓN, PINTURAS Y BARNICES INDUSTRIALES, CERA PARA PISOS, RESINAS ALQUÍDICAS, CAUCHO Y ACABADO DE CUERO",
"FABRICAÇÃO DE TINTAS DE IMPRESSÃO, TINTAS E VERNIZES INDUSTRIAIS, CERA PARA PISO, RESINAS ALQUÍDICAS, BORRACHA, ACABAMENTO EM COURO E CERAS PARA RECOBRIMENTO DE FRUTOS":"FABRICACIÓN DE TINTAS DE IMPRESIÓN, PINTURAS Y BARNICES INDUSTRIALES, CERA PARA PISOS, RESINAS ALQUÍDICAS, CAUCHO, ACABADO DE CUERO Y CERAS PARA RECUBRIMIENTO DE FRUTOS",
"FABRICAÇÃO DE TINTAS DE MARCAÇÃO DE ESTRADA, ADESIVOS HOT-MELT":"FABRICACIÓN DE PINTURAS DE MARCACIÓN VIAL Y ADHESIVOS HOT-MELT",
"FABRICAÇÃO DE TINTAS DE MARCAÇÃO DE ESTRADA, VERNIZES E TINTAS INDUSTRIAIS BASE SOLVENTE, VERNIZES DE PROTEÇÃO DE MADEIRA":"FABRICACIÓN DE PINTURAS DE MARCACIÓN VIAL, BARNICES Y PINTURAS INDUSTRIALES BASE SOLVENTE, Y BARNICES PARA PROTECCIÓN DE MADERA",
"FABRICAÇÃO DE TINTAS E VERNIZES BASE ÁGUA ALCALINA E BASE SOLVENTE":"FABRICACIÓN DE PINTURAS Y BARNICES BASE AGUA ALCALINA Y BASE SOLVENTE",
"FABRICAÇÃO DE ÓLEO DE PINHO, ÉSTERES E RESINAS ESPECIAIS":"FABRICACIÓN DE ACEITE DE PINO, ÉSTERES Y RESINAS ESPECIALES",
"IDEAL PARA FABRICAÇÃO DE CERAS DEPILATÓRIAS":"IDEAL PARA FABRICACIÓN DE CERAS DEPILATORIAS",
"IDEAL PARA FABRICAÇÃO DE RESINAS E ADESIVOS ESPECIAIS QUE DEMANDEM DE ALTA RESISTÊNCIA A CRISTALIZAÇÃO":"IDEAL PARA FABRICACIÓN DE RESINAS Y ADHESIVOS ESPECIALES QUE REQUIERAN ALTA RESISTENCIA A LA CRISTALIZACIÓN",
"IDEAL PARA FABRICAÇÃO DE RESINAS, ADESIVOS, TINTAS E CERAS DEPILATÓRIAS":"IDEAL PARA FABRICACIÓN DE RESINAS, ADHESIVOS, PINTURAS Y CERAS DEPILATORIAS",
"IMPUREZAS":"IMPUREZAS","UMIDADE":"HUMEDAD","SOLUBILIDADE EM AMÔNIA":"SOLUBILIDAD EN AMONÍACO","TEOR DE ABIÉTICO(%)":"CONTENIDO DE ÁCIDO ABIÉTICO (%)","TEOR DE BETA-PINENO":"CONTENIDO DE BETA-PINENO","TEOR DE BICÍCLICOS":"CONTENIDO DE BICÍCLICOS","TEOR DE BREU":"CONTENIDO DE COLOFONIA","TEOR DE TEREBINTINA":"CONTENIDO DE TREMENTINA","SABOR":"SABOR","ODOR":"OLOR","HIDROPERÓXIDO (mEq/g)":"HIDROPERÓXIDO (mEq/g)","ISENTO":"AUSENTE","CARACTERÍSTICO":"CARACTERÍSTICO","CONFORME":"CONFORME","BAIXA":"BAJA",
"A Goma Resina é a matéria-prima base da cadeia do Pinus. Obtida pela remoção de água e impurezas, é submetida à destilação para originar o Breu (fração sólida) e a Terebintina (fração volátil), produtos que alimentam toda a linha de derivados. É o ponto de partida da cadeia. produtiva, garantindo rastreabilidade e qualidade desde a origem.":"La goma-resina es la materia prima base de la cadena del Pinus. Tras eliminar agua e impurezas, se somete a destilación para producir Colofonia (fracción sólida) y Trementina (fracción volátil), productos que alimentan toda la línea de derivados. Es el punto de partida de la cadena productiva, garantizando trazabilidad y calidad desde el origen.",
"O Breu (Colofônia) é a resina natural derivada da destilação da goma resina, composta por ácidos resínicos de boa reatividade. É matéria-prima essencial para resinas sintéticas, sizing de papel, sabões, secantes para tintas, vernizes e adesivos. Sua versatilidade e origem renovável o tornam um pilar da indústria química.":"La colofonia es la resina natural derivada de la destilación de la goma-resina, compuesta por ácidos resínicos de buena reactividad. Es una materia prima esencial para resinas sintéticas, encolado de papel, jabones, secantes para pinturas, barnices y adhesivos. Su versatilidad y origen renovable la convierten en un pilar de la industria química.",
"A Terebintina é o solvente natural renovável obtido na destilação da goma resina. Com excelente poder de dissolução, é amplamente utilizada em tintas, vernizes, fragrâncias, cosméticos e na síntese de resinas e terpenos. Uma alternativa sustentável aos solventes sintéticos, mantendo alto desempenho.":"La trementina es el solvente natural renovable obtenido de la destilación de la goma-resina. Con excelente poder de disolución, se utiliza ampliamente en pinturas, barnices, fragancias, cosméticos y en la síntesis de resinas y terpenos. Es una alternativa sostenible a los solventes sintéticos, manteniendo un alto desempeño.",
"As Resinas Fumáricas são breus modificados com ácido fumárico, desenvolvidos especialmente para tintas de impressão. Com forte adesão ao substrato, secagem rápida e alto brilho, são amplamente utilizadas em tintas flexográficas, rotogravura e offset, além de vernizes e esmaltes sintéticos.":"Las resinas fumáricas son colofonias modificadas con ácido fumárico, desarrolladas especialmente para tintas de impresión. Con fuerte adhesión al sustrato, secado rápido y alto brillo, se utilizan ampliamente en tintas flexográficas, rotograbado y offset, además de barnices y esmaltes sintéticos.",
"As Resinas Maleicas são breus modificados com anidrido maleico, que atuam como agentes modificadores em tintas e vernizes. Proporcionam maior dureza, resistência química e adesão no filme final, com alta compatibilidade com lacas e vernizes nitrocelulósicos.":"Las resinas maleicas son colofonias modificadas con anhídrido maleico, que actúan como agentes modificadores en pinturas y barnices. Proporcionan mayor dureza, resistencia química y adhesión en la película final, con alta compatibilidad con lacas y barnices nitrocelulósicos.",
"O Éster de Glicerol é a resina obtida pela esterificação do breu com glicerina. Com alto poder de adesão e ponto de amolecimento equilibrado, é amplamente utilizado em adesivos hot melt, adesivos sensíveis à pressão, tintas de demarcação viária e ceras depilatórias.":"El éster de glicerol es la resina obtenida por esterificación de la colofonia con glicerina. Con alto poder de adhesión y punto de ablandamiento equilibrado, se utiliza ampliamente en adhesivos hot-melt, adhesivos sensibles a la presión, pinturas de demarcación vial y ceras depilatorias.",
"O Éster de Pentaeritritol é a resina da linha com maior ponto de amolecimento e resistência térmica. Indicado para adesivos hot melt de alta performance, adesivos sensíveis à pressão, tintas e revestimentos, oferece excelente adesividade e estabilidade mesmo em condições severas. Também é substituto natural de resinas hidrocarbonicas para a fabricação de asfalto.":"El éster de pentaeritritol es la resina de la línea con mayor punto de ablandamiento y resistencia térmica. Indicado para adhesivos hot-melt de alto desempeño, adhesivos sensibles a la presión, pinturas y recubrimientos, ofrece excelente adhesividad y estabilidad incluso en condiciones severas. También es un sustituto natural de resinas hidrocarbonadas para la fabricación de asfalto.",
"O Éster de Trietilenoglicol é um éster de breu líquido e viscoso, com excelente aderência, baixa cor e boa resistência ao amarelamento. É amplamente utilizado em adesivos sensíveis à pressão, adesivos hot melt para embalagens, adesivos para construção civil e colagem de pisos.":"El éster de trietilenglicol es un éster de colofonia líquido y viscoso, con excelente adherencia, bajo color y buena resistencia al amarillamiento. Se utiliza ampliamente en adhesivos sensibles a la presión, adhesivos hot-melt para embalajes, adhesivos para construcción civil y pegado de pisos.",
"As Resinas de Marcação Viária são formuladas para tintas termoplásticas de sinalização horizontal de pavimentos. Proporcionam alta adesão, durabilidade e resistência ao desgaste e às intempéries, garantindo demarcações viárias seguras e de longa vida útil.":"Las resinas de marcación vial están formuladas para pinturas termoplásticas de señalización horizontal de pavimentos. Proporcionan alta adhesión, durabilidad y resistencia al desgaste y a la intemperie, garantizando demarcaciones viales seguras y de larga vida útil.",
"O Sabão de Breu, especialmente o desproporcionado, é um agente tensoativo derivado dos ácidos resínicos, com forte presença na indústria da construção civil. Atua como aditivo plastificante-incorporador de ar em concretos e argamassas, melhorando trabalhabilidade, coesão e resistência ao ciclo gelo-degelo. Os sabões com baixo teor de ácido abiético são excelentes agentes emulsificantes para a industria de polimerização de borrachas.":"El jabón de colofonia, especialmente el desproporcionado, es un agente tensioactivo derivado de los ácidos resínicos, con fuerte presencia en la industria de la construcción civil. Actúa como aditivo plastificante e incorporador de aire en concretos y morteros, mejorando trabajabilidad, cohesión y resistencia al ciclo hielo-deshielo. Los jabones con bajo contenido de ácido abiético son excelentes agentes emulsificantes para la industria de polimerización de cauchos.",
"As Emulsões (Dispersões Aquosas) são dispersões de éster de breu em água, livres de solvente e com baixa emissão de VOC. Com excelente compatibilidade com polímeros como borracha natural, acrílico e SBR, são ideais para adesivos sensíveis à pressão em fitas, papel e etiquetas.":"Las emulsiones (dispersiones acuosas) son dispersiones de éster de colofonia en agua, libres de solvente y con baja emisión de VOC. Con excelente compatibilidad con polímeros como caucho natural, acrílico y SBR, son ideales para adhesivos sensibles a la presión en cintas, papel y etiquetas.",
"Aditivos plastificantes para a linha de adesivos e tintas em geral de fonte renovavel e isentos dos ftalatos, parafinas e solventes de petróleo e de origem 100% renovável.":"Aditivos plastificantes para líneas de adhesivos y pinturas en general, de fuente renovable y libres de ftalatos, parafinas y solventes de petróleo, con origen 100% renovable.",
"Adjuvantes para preservação de vitaminas, agrotóxicos e insumos em geral utilizados nas linhas agro protegendo os materiais das perdas por intemperies":"Coadyuvantes para la preservación de vitaminas, productos fitosanitarios e insumos en general utilizados en líneas agro, protegiendo los materiales de pérdidas por intemperie"
}
};

const EXTRA={
en:{
'HOME':'HOME','Home':'Home','Produtos':'Products','Soluções':'Solutions','Qualidade':'Quality','Comércio Internacional':'International Trade','Sobre Nós':'About Us','Contato':'Contact','Quem somos':'Who We Are','Quem Somos':'Who We Are',
'EXPLORE NOSSOS PRODUTOS →':'EXPLORE OUR PRODUCTS →','FALE COM UM ESPECIALISTA ◉':'TALK TO A SPECIALIST ◉','FALAR COM UM ESPECIALISTA ◉':'TALK TO A SPECIALIST ◉','OPERAMOS':'WE OPERATE','ATUAMOS':'WE OPERATE','GLOBALMENTE':'GLOBALLY',
'Produtos de alta qualidade para resinas, adesivos, tintas, borracha e outras aplicações industriais, que combinam segurança, tecnologia e compromisso com o futuro.':'High-quality products for resins, adhesives, paints, rubber and other industrial applications, combining safety, technology and commitment to the future.',
'Produtos de alta qualidade para resinas, adesivos, tintas, borrachas e outras aplicações industriais, que combinam segurança, tecnologia e compromisso com o futuro.':'High-quality products for resins, adhesives, paints, rubber and other industrial applications, combining safety, technology and commitment to the future.',
'Produtos de alta qualidade para resinas, adesivos, tintas, borracha e outras aplicações industriais, com segurança, tecnologia e compromisso com o futuro.':'High-quality products for resins, adhesives, paints, rubber and other industrial applications, with safety, technology and commitment to the future.',
'SOBRE NÓS':'ABOUT US','Quem Somos':'Who We Are','Quem somos':'Who We Are','Nossa história começou na floresta. Há mais de 25 anos trabalhamos com a base florestal de Pinus — começamos como resineiros, extraindo a matéria-prima que hoje processamos nós mesmos.':'Our story began in the forest. For more than 25 years we have worked with the Pinus forestry base — we started as resin tappers, extracting the raw material that we now process ourselves.',
'Dali, verticalizamos para o processamento de breu e terebentina e mais recentemente demos um novo passo: os derivados de breu.':'From there, we vertically integrated into rosin and turpentine processing and, more recently, took a new step: rosin derivatives.',
'Hoje a Green World Chemicals opera em Alambari (SP), processando goma de Pinus para atender indústrias no Brasil e no exterior.':'Today Green World Chemicals operates in Alambari, São Paulo, processing pine gum to serve industries in Brazil and abroad.',
'PORTFÓLIO GREEN WORLD':'GREEN WORLD PORTFOLIO','Nossos':'Our','Produtos':'Products','LINHAS DE PRODUTOS':'PRODUCT LINES','Soluções de origem renovável':'Renewable-source solutions','para diferentes mercados':'for different markets',
'Soluções à base de resina de Pinus para diferentes aplicações industriais. Consulte famílias, códigos, especificações, aplicações e resumo técnico.':'Pine-resin-based solutions for different industrial applications. Browse families, codes, specifications, applications and technical summaries.',
'Conheça as famílias de produtos GREEN WORLD. Selecione uma linha para consultar códigos, especificações, aplicações e solicitar cotação ou amostra.':'Explore GREEN WORLD product families. Select a line to view codes, specifications, applications and request a quote or sample.',
'LINHA':'LINE','APLICAÇÃO':'APPLICATION','TODOS':'ALL','TODAS':'ALL','APLICAÇÕES':'APPLICATIONS','LINHA GREEN WORLD':'GREEN WORLD LINE','Nenhum produto encontrado para os filtros selecionados.':'No products found for the selected filters.',
'SOLICITAR COTAÇÃO →':'REQUEST A QUOTE →','SOLICITAR AMOSTRA →':'REQUEST A SAMPLE →','SOLICITAR DOCUMENTAÇÃO TÉCNICA →':'REQUEST TECHNICAL DOCUMENTATION →','Consulte nossa equipe comercial.':'Contact our sales team.',
'PONTO DE AMOLECIMENTO (°C)':'SOFTENING POINT (°C)','PONTO DE AMOLECIMENTO °C':'SOFTENING POINT °C','ACIDEZ (mgKOH/G)':'ACIDITY (mgKOH/g)','CRISTALIZAÇÃO - h':'CRYSTALLIZATION - h','VISCOSIDADE GARDNER':'GARDNER VISCOSITY','VISCOSIDADE (cPs)':'VISCOSITY (cPs)','VISCOSIDADE (cPs)C- GARDNER':'VISCOSITY (cPs) - GARDNER',
'Precisa de uma cotação?':'Need a quote?','Nossa equipe está pronta para atender você.':'Our team is ready to assist you.','Soluções químicas de alta qualidade para um mundo em constante evolução.':'High-quality chemical solutions for a constantly evolving world.','NAVEGAÇÃO':'NAVIGATION','SUPORTE':'SUPPORT','Fale Conosco':'Contact Us','Solicitar Cotação':'Request a Quote','Política de Privacidade':'Privacy Policy','Todos os direitos reservados.':'All rights reserved.','© 2026 GREEN WORLD. Todos os direitos reservados.':'© 2026 GREEN WORLD. All rights reserved.',
'Cotação':'Quote','Amostra':'Sample','Topo':'Top','Abrir contatos':'Open contacts','Fechar contatos':'Close contacts','Contatos':'Contacts'
},
es:{
'HOME':'INICIO','Home':'Inicio','Produtos':'Productos','Soluções':'Soluciones','Qualidade':'Calidad','Comércio Internacional':'Comercio Internacional','Sobre Nós':'Sobre Nosotros','Contato':'Contacto','Quem somos':'Quiénes Somos','Quem Somos':'Quiénes Somos',
'EXPLORE NOSSOS PRODUTOS →':'EXPLORA NUESTROS PRODUCTOS →','FALE COM UM ESPECIALISTA ◉':'HABLA CON UN ESPECIALISTA ◉','FALAR COM UM ESPECIALISTA ◉':'HABLA CON UN ESPECIALISTA ◉','OPERAMOS':'OPERAMOS','ATUAMOS':'ACTUAMOS','GLOBALMENTE':'GLOBALMENTE',
'Produtos de alta qualidade para resinas, adesivos, tintas, borracha e outras aplicações industriais, que combinam segurança, tecnologia e compromisso com o futuro.':'Productos de alta calidad para resinas, adhesivos, pinturas, caucho y otras aplicaciones industriales, combinando seguridad, tecnología y compromiso con el futuro.',
'Produtos de alta qualidade para resinas, adesivos, tintas, borrachas e outras aplicações industriais, que combinam segurança, tecnologia e compromisso com o futuro.':'Productos de alta calidad para resinas, adhesivos, pinturas, caucho y otras aplicaciones industriales, combinando seguridad, tecnología y compromiso con el futuro.',
'Produtos de alta qualidade para resinas, adesivos, tintas, borracha e outras aplicações industriais, com segurança, tecnologia e compromisso com o futuro.':'Productos de alta calidad para resinas, adhesivos, pinturas, caucho y otras aplicaciones industriales, con seguridad, tecnología y compromiso con el futuro.',
'SOBRE NÓS':'SOBRE NOSOTROS','Quem Somos':'Quiénes Somos','Quem somos':'Quiénes Somos','Nossa história começou na floresta. Há mais de 25 anos trabalhamos com a base florestal de Pinus — começamos como resineiros, extraindo a matéria-prima que hoje processamos nós mesmos.':'Nuestra historia comenzó en el bosque. Desde hace más de 25 años trabajamos con la base forestal de Pinus — empezamos como resineros, extrayendo la materia prima que hoy procesamos nosotros mismos.',
'Dali, verticalizamos para o processamento de breu e terebentina e mais recentemente demos um novo passo: os derivados de breu.':'A partir de allí, integramos verticalmente el procesamiento de colofonia y trementina y, más recientemente, dimos un nuevo paso: los derivados de colofonia.',
'Hoje a Green World Chemicals opera em Alambari (SP), processando goma de Pinus para atender indústrias no Brasil e no exterior.':'Hoy Green World Chemicals opera en Alambari, São Paulo, procesando goma de Pinus para atender industrias en Brasil y en el exterior.',
'PORTFÓLIO GREEN WORLD':'PORTAFOLIO GREEN WORLD','Nossos':'Nuestros','Produtos':'Productos','LINHAS DE PRODUTOS':'LÍNEAS DE PRODUCTOS','Soluções de origem renovável':'Soluciones de origen renovable','para diferentes mercados':'para diferentes mercados',
'Soluções à base de resina de Pinus para diferentes aplicações industriais. Consulte famílias, códigos, especificações, aplicações e resumo técnico.':'Soluciones a base de resina de Pinus para diferentes aplicaciones industriales. Consulte familias, códigos, especificaciones, aplicaciones y resúmenes técnicos.',
'Conheça as famílias de produtos GREEN WORLD. Selecione uma linha para consultar códigos, especificações, aplicações e solicitar cotação ou amostra.':'Conozca las familias de productos GREEN WORLD. Seleccione una línea para consultar códigos, especificaciones, aplicaciones y solicitar una cotización o muestra.',
'LINHA':'LÍNEA','APLICAÇÃO':'APLICACIÓN','TODOS':'TODOS','TODAS':'TODAS','APLICAÇÕES':'APLICACIONES','LINHA GREEN WORLD':'LÍNEA GREEN WORLD','Nenhum produto encontrado para os filtros selecionados.':'No se encontraron productos para los filtros seleccionados.',
'SOLICITAR COTAÇÃO →':'SOLICITAR COTIZACIÓN →','SOLICITAR AMOSTRA →':'SOLICITAR MUESTRA →','SOLICITAR DOCUMENTAÇÃO TÉCNICA →':'SOLICITAR DOCUMENTACIÓN TÉCNICA →','Consulte nossa equipe comercial.':'Consulte a nuestro equipo comercial.',
'PONTO DE AMOLECIMENTO (°C)':'PUNTO DE ABLANDAMIENTO (°C)','PONTO DE AMOLECIMENTO °C':'PUNTO DE ABLANDAMIENTO °C','ACIDEZ (mgKOH/G)':'ACIDEZ (mgKOH/g)','CRISTALIZAÇÃO - h':'CRISTALIZACIÓN - h','VISCOSIDADE GARDNER':'VISCOSIDAD GARDNER','VISCOSIDADE (cPs)':'VISCOSIDAD (cPs)','VISCOSIDADE (cPs)C- GARDNER':'VISCOSIDAD (cPs) - GARDNER',
'Precisa de uma cotação?':'¿Necesita una cotización?','Nossa equipe está pronta para atender você.':'Nuestro equipo está listo para atenderle.','Soluções químicas de alta qualidade para um mundo em constante evolução.':'Soluciones químicas de alta calidad para un mundo en constante evolución.','NAVEGAÇÃO':'NAVEGACIÓN','SUPORTE':'SOPORTE','Fale Conosco':'Contáctenos','Solicitar Cotação':'Solicitar Cotización','Política de Privacidade':'Política de Privacidad','Todos os direitos reservados.':'Todos los derechos reservados.','© 2026 GREEN WORLD. Todos os direitos reservados.':'© 2026 GREEN WORLD. Todos los derechos reservados.',
'Cotação':'Cotización','Amostra':'Muestra','Topo':'Arriba','Abrir contatos':'Abrir contactos','Fechar contatos':'Cerrar contactos','Contatos':'Contactos'
}
};

const PHRASES={
en:[
['IDEAL PARA FABRICAÇÃO','IDEAL FOR MANUFACTURING'],['IDEAL PARA FBARICAÇÃO','IDEAL FOR MANUFACTURING'],['FABRICAÇÃO DE','MANUFACTURING OF'],['PONTO DE AMOLECIMENTO','SOFTENING POINT'],['COR GARDNER','GARDNER COLOR'],['ÍNDICE DE ACIDEZ','ACID NUMBER'],['ACIDEZ','ACIDITY'],['CRISTALIZAÇÃO','CRYSTALLIZATION'],['VISCOSIDADE','VISCOSITY'],['DENSIDADE','DENSITY'],['TEOR DE SÓLIDOS','SOLIDS CONTENT'],['TEOR MÍNIMO','MINIMUM CONTENT'],['TEOR','CONTENT'],['MÍNIMO','MINIMUM'],['MÁXIMO','MAXIMUM'],['MÍN','MIN'],['MÁX','MAX'],['RESINAS','RESINS'],['ADESIVOS','ADHESIVES'],['TINTAS','PAINTS'],['VERNIZES','VARNISHES'],['BORRACHAS','RUBBER'],['PNEUS','TIRES'],['CERAS DEPILATÓRIAS','DEPILATORY WAXES'],['MARCAÇÃO VIÁRIA','ROAD MARKING'],['CONSTRUÇÃO CIVIL','CONSTRUCTION'],['GOMA RESINA','PINE GUM'],['TEREBINTINA','TURPENTINE'],['BREU','ROSIN'],['COLOFÔNIA','COLOPHONY'],['DERIVADOS','DERIVATIVES'],['ÁGUA','WATER'],['SOLVENTE','SOLVENT'],['ALTA RESISTENCIA','HIGH RESISTANCE'],['ALTA RESISTÊNCIA','HIGH RESISTANCE'],['RESISTÊNCIA','RESISTANCE'],['QUÍMICA','CHEMICAL'],['QUIMICAMENTE','CHEMICALLY'],['PRODUTO','PRODUCT'],['MATÉRIA-PRIMA','RAW MATERIAL'],['APLICAÇÕES INDUSTRIAIS','INDUSTRIAL APPLICATIONS'],['ORIGEM RENOVÁVEL','RENEWABLE ORIGIN'],['livres de solvente','solvent-free'],['baixa emissão de VOC','low VOC emissions'],['excelente compatibilidade','excellent compatibility'],['são ideais para','are ideal for'],['proveniente exclusivamente da destilação','obtained exclusively from the distillation'],['sem nenhuma modificação química','without any chemical modification'],['modificado e estabilizado quimicamente','chemically modified and stabilized'],['para proporcionar maior resistência à cristalização','to provide greater resistance to crystallization'],['Consulte nossa equipe','Contact our team'],['NOSSOS','OUR'],['NOSSO','OUR'],['NOSSA','OUR'],['NOSSAS','OUR'],['PRODUTOS','PRODUCTS'],['PRODUTO','PRODUCT'],['LINHAS','LINES'],['LINHA','LINE'],['APLICAÇÕES','APPLICATIONS'],['APLICAÇÃO','APPLICATION'],['SOLUÇÕES','SOLUTIONS'],['QUALIDADE','QUALITY'],['COTAÇÃO','QUOTE'],['AMOSTRA','SAMPLE'],['DOCUMENTAÇÃO TÉCNICA','TECHNICAL DOCUMENTATION'],['FABRICAÇÃO','MANUFACTURING'],['CONTROLE DE QUALIDADE','QUALITY CONTROL'],['SEGURANÇA','SAFETY'],['RASTREABILIDADE','TRACEABILITY'],['LABORATÓRIO PRÓPRIO','IN-HOUSE LABORATORY'],['PROFISSIONAIS QUALIFICADOS','QUALIFIED PROFESSIONALS'],['PROCESSOS SEGUROS','SAFE PROCESSES'],['MELHORIA CONTÍNUA','CONTINUOUS IMPROVEMENT']
],
es:[
['IDEAL PARA FABRICAÇÃO','IDEAL PARA FABRICACIÓN'],['IDEAL PARA FBARICAÇÃO','IDEAL PARA FABRICACIÓN'],['FABRICAÇÃO DE','FABRICACIÓN DE'],['PONTO DE AMOLECIMENTO','PUNTO DE ABLANDAMIENTO'],['COR GARDNER','COLOR GARDNER'],['ÍNDICE DE ACIDEZ','ÍNDICE DE ACIDEZ'],['ACIDEZ','ACIDEZ'],['CRISTALIZAÇÃO','CRISTALIZACIÓN'],['VISCOSIDADE','VISCOSIDAD'],['DENSIDADE','DENSIDAD'],['TEOR DE SÓLIDOS','CONTENIDO DE SÓLIDOS'],['TEOR MÍNIMO','CONTENIDO MÍNIMO'],['TEOR','CONTENIDO'],['MÍNIMO','MÍNIMO'],['MÁXIMO','MÁXIMO'],['MÍN','MÍN'],['MÁX','MÁX'],['RESINAS','RESINAS'],['ADESIVOS','ADHESIVOS'],['TINTAS','PINTURAS'],['VERNIZES','BARNICES'],['BORRACHAS','CAUCHOS'],['PNEUS','NEUMÁTICOS'],['CERAS DEPILATÓRIAS','CERAS DEPILATORIAS'],['MARCAÇÃO VIÁRIA','MARCACIÓN VIAL'],['CONSTRUÇÃO CIVIL','CONSTRUCCIÓN CIVIL'],['TEREBINTINA','TREMENTINA'],['BREU','COLOFONIA'],['DERIVADOS','DERIVADOS'],['ÁGUA','AGUA'],['SOLVENTE','SOLVENTE'],['ALTA RESISTENCIA','ALTA RESISTENCIA'],['ALTA RESISTÊNCIA','ALTA RESISTENCIA'],['RESISTÊNCIA','RESISTENCIA'],['QUÍMICA','QUÍMICA'],['QUIMICAMENTE','QUÍMICAMENTE'],['PRODUTO','PRODUCTO'],['MATÉRIA-PRIMA','MATERIA PRIMA'],['APLICAÇÕES INDUSTRIAIS','APLICACIONES INDUSTRIALES'],['ORIGEM RENOVÁVEL','ORIGEN RENOVABLE'],['livres de solvente','libres de solvente'],['baixa emissão de VOC','baja emisión de VOC'],['excelente compatibilidade','excelente compatibilidad'],['são ideais para','son ideales para'],['proveniente exclusivamente da destilação','proveniente exclusivamente de la destilación'],['sem nenhuma modificação química','sin ninguna modificación química'],['modificado e estabilizado quimicamente','modificado y estabilizado químicamente'],['para proporcionar maior resistência à cristalização','para proporcionar mayor resistencia a la cristalización'],['Consulte nossa equipe','Consulte a nuestro equipo'],['NOSSOS','NUESTROS'],['NOSSO','NUESTRO'],['NOSSA','NUESTRA'],['NOSSAS','NUESTRAS'],['PRODUTOS','PRODUCTOS'],['PRODUTO','PRODUCTO'],['LINHAS','LÍNEAS'],['LINHA','LÍNEA'],['APLICAÇÕES','APLICACIONES'],['APLICAÇÃO','APLICACIÓN'],['SOLUÇÕES','SOLUCIONES'],['QUALIDADE','CALIDAD'],['COTAÇÃO','COTIZACIÓN'],['AMOSTRA','MUESTRA'],['DOCUMENTAÇÃO TÉCNICA','DOCUMENTACIÓN TÉCNICA'],['FABRICAÇÃO','FABRICACIÓN'],['CONTROLE DE QUALIDADE','CONTROL DE CALIDAD'],['SEGURANÇA','SEGURIDAD'],['RASTREABILIDADE','TRAZABILIDAD'],['LABORATÓRIO PRÓPRIO','LABORATORIO PROPIO'],['PROFISSIONAIS QUALIFICADOS','PROFESIONALES CALIFICADOS'],['PROCESSOS SEGUROS','PROCESOS SEGUROS'],['MELHORIA CONTÍNUA','MEJORA CONTINUA']
]};


const PRODUCT_EXACT={
  en:{
    'COR GARDNER':'GARDNER COLOR','ACIDEZ':'ACIDITY','DENSIDADE':'DENSITY','PONTO DE AMOLECIMENTO':'SOFTENING POINT','TEOR DE SÓLIDOS':'SOLIDS CONTENT','pH':'pH',
    'MATÉRIA-PRIMA':'RAW MATERIAL','BREU / COLOFÔNIA':'ROSIN / COLOPHONY','DERIVADOS DE BREU':'ROSIN DERIVATIVES','ÉSTERES DE BREU':'ROSIN ESTERS','RESINAS ESPECIAIS':'SPECIAL RESINS','SABÕES DE BREU':'ROSIN SOAPS','DISPERSÕES AQUOSAS':'AQUEOUS DISPERSIONS','PLASTIFICANTES NATURAIS':'NATURAL PLASTICIZERS','SOLUÇÕES AGRO':'AGRICULTURAL SOLUTIONS','INTERMEDIÁRIOS':'INTERMEDIATES'
  },
  es:{
    'COR GARDNER':'COLOR GARDNER','ACIDEZ':'ACIDEZ','DENSIDADE':'DENSIDAD','PONTO DE AMOLECIMENTO':'PUNTO DE ABLANDAMIENTO','TEOR DE SÓLIDOS':'CONTENIDO DE SÓLIDOS','pH':'pH',
    'MATÉRIA-PRIMA':'MATERIA PRIMA','BREU / COLOFÔNIA':'COLOFONIA','DERIVADOS DE BREU':'DERIVADOS DE COLOFONIA','ÉSTERES DE BREU':'ÉSTERES DE COLOFONIA','RESINAS ESPECIAIS':'RESINAS ESPECIALES','SABÕES DE BREU':'JABONES DE COLOFONIA','DISPERSÕES AQUOSAS':'DISPERSIONES ACUOSAS','PLASTIFICANTES NATURAIS':'PLASTIFICANTES NATURALES','SOLUÇÕES AGRO':'SOLUCIONES AGRÍCOLAS','INTERMEDIÁRIOS':'INTERMEDIOS'
  }
};

let current='pt';
const originals=new WeakMap();
function urlLang(){try{const v=new URLSearchParams(location.search).get('lang');return ['pt','en','es'].includes(v)?v:null}catch(e){return null}}
function storageGet(){try{return localStorage.getItem('gw-lang')}catch(e){return null}}
function storageSet(v){try{localStorage.setItem('gw-lang',v)}catch(e){}}
function syncInternalLinks(lang){
  document.querySelectorAll('a[href]').forEach(a=>{
    const raw=a.getAttribute('href');
    if(!raw || raw.startsWith('#') || raw.startsWith('mailto:') || raw.startsWith('tel:') || raw.startsWith('javascript:') || /^https?:\/\//i.test(raw) || raw.startsWith('//')) return;
    try{
      const u=new URL(raw, location.href);
      if(u.origin!==location.origin) return;
      if(!/\.html$/i.test(u.pathname) && !u.pathname.endsWith('/')) return;
      u.searchParams.set('lang',lang);
      a.setAttribute('href',u.pathname.split('/').pop() + (u.search||'') + (u.hash||''));
    }catch(e){}
  });
}
function norm(s){return String(s||'').replace(/\s+/g,' ').trim();}
function translateRaw(raw,lang){
  if(lang==='pt') return raw;
  const lead=(raw.match(/^\s*/)||[''])[0], tail=(raw.match(/\s*$/)||[''])[0], n=norm(raw);
  if(!n) return raw;
  let out=(PRODUCT_EXACT[lang]||{})[n] || (EXTRA[lang]||{})[n] || (FULLTEXT[lang]||{})[n] || (EXACT[lang]||{})[n] || (FAMILY[lang]||{})[n] || (APP[lang]||{})[n];
  if(!out){
    out=n;
    for(const [a,b] of PHRASES[lang]||[]) out=out.split(a).join(b);
    if(lang==='en'){ out=out.replace(/(\d+) produtos?/gi,'$1 products').replace(/(\d+) linhas?/gi,'$1 lines').replace(/(\d+) aplicações?/gi,'$1 applications'); }
    if(lang==='es'){ out=out.replace(/(\d+) produtos?/gi,'$1 productos').replace(/(\d+) linhas?/gi,'$1 líneas').replace(/(\d+) aplicações?/gi,'$1 aplicaciones'); }
  }
  return lead+out+tail;
}
function shouldSkip(node){
  const p=node.parentElement;
  return !p || /^(SCRIPT|STYLE|NOSCRIPT|OPTION)$/.test(p.tagName) || p.closest('[data-no-translate]');
}
function processTextNode(node,lang){
  if(shouldSkip(node)||!norm(node.nodeValue)) return;
  if(!originals.has(node)) originals.set(node,node.nodeValue);
  node.nodeValue=translateRaw(originals.get(node),lang);
}
function process(root,lang){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  let n; while(n=walker.nextNode()) processTextNode(n,lang);
}
function translateAttributes(lang){
  const search=document.getElementById('productSearch');
  if(search){ const s=lang==='en'?'Search product, code or application':lang==='es'?'Buscar producto, código o aplicación':'Buscar produto, código ou aplicação'; search.placeholder=s+'...'; search.setAttribute('aria-label',s); const lab=document.querySelector('label[for="productSearch"]'); if(lab) lab.textContent=s; }
  const mt=document.querySelector('.menu-toggle'); if(mt) mt.setAttribute('aria-label',lang==='en'?'Open menu':lang==='es'?'Abrir menú':'Abrir menu');
  const dock=document.querySelector('.contact-dock'); if(dock) dock.setAttribute('aria-label',lang==='en'?'Contact shortcuts':lang==='es'?'Accesos de contacto':'Atalhos de contato');
  document.title = location.pathname.includes('produtos') ? (lang==='en'?'Products | Green World':lang==='es'?'Productos | Green World':'Produtos | Green World') : (lang==='en'?'Green World | Chemical Solutions':lang==='es'?'Green World | Soluciones químicas':'Green World | Soluções químicas');
}
function updateSwitcher(lang){
  document.querySelectorAll('[data-language-switcher]').forEach(sw=>{
    const sel=sw.querySelector('.language-native'); if(sel) sel.value=lang;
    const flag=sw.querySelector('.language-current .language-flag'); if(flag) flag.textContent=FLAGS[lang];
    const lab=sw.querySelector('.language-current-label'); if(lab) lab.textContent=LABELS[lang];
    sw.querySelectorAll('.language-option').forEach(o=>{const a=o.dataset.lang===lang;o.classList.toggle('active',a);o.setAttribute('aria-selected',a?'true':'false');});
  });
  document.querySelectorAll('[data-set-lang]').forEach(b=>{
    const a=b.dataset.setLang===lang; b.classList.toggle('active',a); b.setAttribute('aria-pressed',a?'true':'false');
  });
}
function waMessage(kind,lang,code){
  const base={
    pt:{quote:'Olá! Gostaria de solicitar uma cotação',sample:'Olá! Gostaria de solicitar uma amostra',docs:'Olá! Gostaria de solicitar a documentação técnica',general:'Olá! Gostaria de falar com a equipe comercial da Green World.'},
    en:{quote:'Hello! I would like to request a quote',sample:'Hello! I would like to request a sample',docs:'Hello! I would like to request the technical documentation',general:"Hello! I would like to speak with Green World's sales team."},
    es:{quote:'¡Hola! Me gustaría solicitar una cotización',sample:'¡Hola! Me gustaría solicitar una muestra',docs:'¡Hola! Me gustaría solicitar la documentación técnica',general:'¡Hola! Me gustaría hablar con el equipo comercial de Green World.'}
  }[lang];
  if(kind==='general') return base.general;
  return code ? `${base[kind]} ${lang==='en'?'for product':lang==='es'?'del producto':'do produto'} ${code} ${lang==='en'?'from':lang==='es'?'de':'da'} Green World.` : `${base[kind]} ${lang==='en'?'from':lang==='es'?'a':'com a'} Green World.`;
}
function updateWhatsApp(lang){
  const whatsappNumber=(lang==='en'||lang==='es')?'5515996557146':'5515996681701';
  const url=m=>'https://wa.me/'+whatsappNumber+'?text='+encodeURIComponent(m);
  document.querySelectorAll('.whatsapp-quote').forEach(a=>a.href=url(waMessage('quote',lang)));
  document.querySelectorAll('.whatsapp-sample').forEach(a=>a.href=url(waMessage('sample',lang)));
  document.querySelectorAll('.whatsapp-general').forEach(a=>a.href=url(waMessage('general',lang)));
  document.querySelectorAll('.quote-action-btn,.sample-btn,.docs-btn').forEach(a=>{
    const row=a.closest('.family-product-row'); const code=row&&row.querySelector('.product-code-pill')?row.querySelector('.product-code-pill').textContent.trim():'';
    const kind=a.classList.contains('sample-btn')?'sample':a.classList.contains('docs-btn')?'docs':'quote';
    a.href=url(waMessage(kind,lang,code));
  });
}
function setLanguage(lang){
  if(!['pt','en','es'].includes(lang)) lang='pt';
  current=lang; storageSet(lang); document.documentElement.lang=lang==='pt'?'pt-BR':lang;
  process(document.body,lang); translateAttributes(lang); updateSwitcher(lang); updateWhatsApp(lang); syncInternalLinks(lang);
  try{ if(typeof window.GreenWorldProductsRender==='function') window.GreenWorldProductsRender(); }catch(e){}
  document.dispatchEvent(new CustomEvent('gw-language-change',{detail:{lang}}));
}
function initSwitcher(){
  document.querySelectorAll('[data-language-switcher]').forEach(sw=>{
    const btn=sw.querySelector('.language-current');
    if(btn) btn.addEventListener('click',e=>{e.stopPropagation();const open=!sw.classList.contains('open');document.querySelectorAll('[data-language-switcher]').forEach(x=>x.classList.remove('open'));sw.classList.toggle('open',open);btn.setAttribute('aria-expanded',open?'true':'false');});
    sw.querySelectorAll('.language-option').forEach(o=>o.addEventListener('click',e=>{e.preventDefault();setLanguage(o.dataset.lang);sw.classList.remove('open');if(btn)btn.setAttribute('aria-expanded','false');}));
    const sel=sw.querySelector('.language-native'); if(sel) sel.addEventListener('change',()=>setLanguage(sel.value));
  });
  document.querySelectorAll('[data-set-lang]').forEach(b=>b.addEventListener('click',e=>{
    e.preventDefault(); setLanguage(b.dataset.setLang);
  }));
  document.addEventListener('click',()=>document.querySelectorAll('[data-language-switcher]').forEach(sw=>{sw.classList.remove('open');const b=sw.querySelector('.language-current');if(b)b.setAttribute('aria-expanded','false');}));
}
initSwitcher();
setLanguage(urlLang()||storageGet()||'pt');
const obs=new MutationObserver(muts=>{
  let touched=false;
  for(const m of muts) for(const n of m.addedNodes){ if(n.nodeType===3) processTextNode(n,current); else if(n.nodeType===1) process(n,current); touched=true; }
  if(touched) updateWhatsApp(current);
});
obs.observe(document.body,{childList:true,subtree:true});
window.GreenWorldLanguage={set:setLanguage,get:()=>current,translate:(text,lang=current)=>translateRaw(String(text??''),lang)};
})();
